#+TITLE: using corfu overlay
#+AUTHOR: Luis Henriquez-Perez

Here I will document my use of .  Unlike [[][mono-complete]] it worked as I
expected when I modified [[file:/home/luis/Documents/MyBlog/org/documentation/29.4-helpful-variable--completion-at-point-functions.html][completion-at-point-functions]].  I tested it by trying to.  I will say I did fee a lag when typging  do not know if that was just me or what.

Donec vitae dolor.   Fusce sagittis, libero non molestie mollis, magna orci ultrices dolor, at vulputate neque nulla lacinia eros.   Mauris ac felis vel velit tristique imperdiet.

Nullam eu ante vel est convallis dignissim.  Fusce suscipit, wisi nec facilisis
facilisis, est dui fermentum leo, quis tempor ligula erat quis odio.  Nunc porta
vulputate tellus.  Nunc rutrum turpis sed pede.  Sed bibendum.  Aliquam posuere.
Nunc aliquet, augue nec adipiscing interdum, lacus tellus malesuada massa, quis
varius mi purus non odio.  Pellentesque condimentum, magna ut suscipit
hendrerit, ipsum augue ornare nulla, non luctus diam neque sit amet urna.
Curabitur vulputate vestibulum lorem.  Fusce sagittis, libero non molestie
mollis, magna orci ultrices dolor, at vulputate neque nulla lacinia eros.  Sed
id ligula quis est convallis tempor.  Curabitur lacinia pulvinar nibh.  Nam a
sapien.

Donec adipiscing Pellentesque 

#+begin_src emacs-lisp
(opt! corfu-auto nil)
#+end_src

#+begin_src emacs-lisp
(add-hook 'completion-at-point-functions #'cape-dabbrev nil 'local)
(remove-hook 'completion-at-point-functions #'pcomplete-completions-at-point 'local)
#+end_src
