#+title:troubleshooting keybinding
#+author:Luis Henriquez-Perez

I have a particular keybinding that is not working.  I tell you Emacs
keybindings are already complex but when you add evil on top of it, its on a
whole different level.  One of the most compelling reasons not to use evil is
because the how much more complex evil keybindings are from normal Emacs
keybindings.

This does not work.  This uses [[file:../documentation/29.4-helpful-callable--bind!.html][bind!]] a macro I write to try to generalize
keybindings in [[file:../documentation/29.4-155-base-bind-macros.html][155-base-bind-macros.el]].  The expansin of this macro is akin to
~(evil-define-key '(normal visual) global-map "g r" #'+evil-eval-replace-operator)~.

#+begin_src emacs-lisp
(bind! (n v) "g r" #'+evil-eval-replace-operator)
#+end_src

Also neither does this.

#+begin_src emacs-lisp
;; I do not know why but I have to specifically define this for emacs-lisp-mode.
(bind! emacs-lisp-mode-map (n v) "g r" #'+evil-eval-replace-operator)
#+end_src

Honestly with these two bindings not working I am a bit stumped.

First debugging step is to find where this binding to xref is set and to study
how it is set.  And upon some looking I found it is defined in [[https://github.com/emacs-evil/evil-collection][evil-collection]],
specifically in it is elisp keybindings folder.  And looking into emacs-lisp.  I
still do not understand but a workaround is simply to set.

#+begin_src emacs-lisp
#+end_src

