:PROPERTIES:
:ID:       20250214T100729.180853
:END:
#+title: Trying Out Elpaca
#+author: Luis Henriquez-Perez

So I have tried [[][Pelpaca]].  It was not my first time trying it out.  I
wanted to see if could make it work.  Elpaca is one of the packages I have
always wanted to make work.  But I have not been able to get through the qualms
I have with it.

* missing timing during first package install
:PROPERTIES:
:ID:       20250206T090437.783506
:END:

So the last time I tried elpaca I was really put off by the installation of
packages for the first time.  One of the elpaca's selling points is that it
installs packages asynchronously and in separate processes.  Generally this is
good.  In fact I think one of the biggest annoyances of =package.el= is that it
installs packages synchronously, blocking Emacs until its done.  If you are
installing packages in your current Emacs session.  The problem I have with this
is that the user has no idea when the package installation will be done.  Since
the installations do not block Emacs, Emacs continues with its init process.
Assuming you are installing a non-trivial number of packages, the init process
will be over and code you had relying on the init process that required certain
packages will have missed timing.  For example, I enable =evil-mode= and
=vertico-mode= in [[][Vemacs-startup-hook]].  Since these packages are not
installed yet, your hooks will not work and your configuration will not have
[[][Pevil]] or [[][Pvertico]] enabled at startup.  So anything that relies on
certain packages will break.  For bootstrapping Emacs packages it is actually
useful to.

* unexplicable =elpaca-wait=
:PROPERTIES:
:ID:       20250205T170130.220650
:END:

I had created an [[][issue]] in the past asking for elpaca to be able to
optionally install packages synchronously.  I was thinking I could install
packages synchronously the first time I am bootstrapping my configuration, and
then I could just use the asynchronous installing in session.  The author did
not want to and instead added =elpaca-wait= which was a while loop that would
block emacs until the registered elpaca packages were done.  Right now the
recommendation is to use =elpaca-wait= after the packages you need for startup.

* inconsistent success when installing packages

I have tried installing packages.

* conclusion

For now I will stick to =package.el=.  Despite how badly Radian criticized
package.el, the truth is it is not that bad at least considering how eccentric
built-in emacs packages can be.  It at least does its basic job and installs
packages.  The lack of asynchronous support is annoying but bearable.  I do want
the reproducibility that =elpaca= can offer me but not at the price of losing
stability at startup.  While =package.el= is quircky it is simple so I can.

My recommendation is if you are using elpaca use some script to bootstrap your
packages separately and then to start Emacs with the packages already installed.
The author did not like this idea and admittedly it is a bit annoying but what
other way is there?
