#+title:revisiting stopping abbrev from expanding
#+author:Luis Henriquez-Perez

In a [[file:2025-01-20T04.57.23_stopping-abbrev-from-expanding-on-newline.org][previous post]] I had looked at unexpected behavior that allowed abbrevs to
expand even if they were several lines before my cursor.  There I fixed it by
changing the [[][:regexp property]] of the abbrev table to make sure that
abbrevs only expanded with spaces.  But as I had been revising that post it
occurred to me that maybe that was not the problem or atleast not the only
problem.  I think it might be O.K. to have an abbrev expand if its in the
previous line.  I mean this makes sense.  But at least I do not expect it to
happen across multiple lines.

Some context: that abbrev had an [[][:enable-property]] set to
[[file:../documentation/29.4-helpful-callable--oo-use-text-abbrev-p.html][oo-use-text-abbrev-p]].  This means that abbrev would only expand if the current
major mode was derived from text mode or if the cursor was in a string or
docstring.  The example is in emacs-lisp-mode so the first condition will always
be false.  Although the symbol "args" was not in a docstring, the reason it was
still expanded was because my cursor was in a docstring.  That is not what my
intention was.  My intention is that only words in a docstring or comment should
expand.  The reason I did not notice this before is that the majority of the
time the cursor being in the docstring or comment usually means the previous
abbrev.  The example I encountered was a rare edge case.  So the
underlying problem here is that with these enable properties.  So I need to
figure out how to code it so that if.  For this I need to review how abbrev
expansion works again.

I think the pertinent function is [[file:../documentation/29.4-helpful-callable--abbrev--default-expand.html][abbrev--default-expand]].  It collects
information about the abbrev before point with the aptly named
[[file:../documentation/29.4-helpful-callable--abbrev--before-point.html][abbrev--before-point]] and records the information before actually inserting the
abbrev.

#+begin_src emacs-lisp
(defun abbrev--default-expand ()
  "Default function to use for `abbrev-expand-function'.
This also respects the obsolete wrapper hook `abbrev-expand-functions'.
\(See `with-wrapper-hook' for details about wrapper hooks.)
Calls `abbrev-insert' to insert any expansion, and returns what it does."
  (subr--with-wrapper-hook-no-warnings abbrev-expand-functions ()
                                       (pcase-let ((`(,sym ,name ,wordstart ,wordend) (abbrev--before-point)))
                                         (when sym
                                           (let ((startpos (copy-marker (point) t))
                                                 (endmark (copy-marker wordend t)))
                                             (unless (or ;; executing-kbd-macro
                                                      noninteractive
                                                      (window-minibuffer-p))
                                               ;; Add an undo boundary, in case we are doing this for
                                               ;; a self-inserting command which has avoided making one so far.
                                               (undo-boundary))
                                             ;; Now sym is the abbrev symbol.
                                             (setq last-abbrev-text name)
                                             (setq last-abbrev sym)
                                             (setq last-abbrev-location wordstart)
                                             ;; If this abbrev has an expansion, delete the abbrev
                                             ;; and insert the expansion.
                                             (prog1
                                                 (abbrev-insert sym name wordstart wordend)
                                               ;; Yuck!!  If expand-abbrev is called with point slightly
                                               ;; further than the end of the abbrev, move point back to
                                               ;; where it started.
                                               (if (and (> startpos endmark)
                                                        (= (point) endmark)) ;Obey skeletons that move point.
                                                   (goto-char startpos))))))))
#+end_src

So my thinking is I need to advise =abbrev-insert= so it does nothing if the
abbrevs enable function does not return non-nil from =last-abbrev-location=.  My
lingering doubt with this is that I will be polluting the.  In essence I am
adding another check to determine if the abbrev will expand.

On second thought I think I should just make =abbrev--before-point= return false
in this case.  It finds the first table that satisfies enable function.  It
already checks the enable property but I want it to also check the enable
property after it finds a proper abbrev too, at it is start point.

Unfortunately this is one of the cases where there is no great place to advise.
I mean this could still be done with advice but it would be inefficient because
I would have to implement certain code twice.

The following block the part of the body of =abbrev--before-point= that actually
checks each active abbrev table until a valid abbrev is found.
#+begin_src emacs-lisp
(while (and tables (not (car res)))
  (let* ((table (pop tables))
         (enable-fun (abbrev-table-get table :enable-function)))
    (setq tables (append (abbrev-table-get table :parents) tables))
    (setq res
          (and
           ;; Check whether enable function works at point if there is one.
           (or (not enable-fun) (funcall enable-fun))
           ;; Check whether the table regexp works at point, again if there is
           ;; one.  Also if there is one record the word in question.
           (let ((re (abbrev-table-get table :regexp)))
             (if (null re)
                 ;; We used to default `re' to "\\<\\(\\w+\\)\\W*"
                 ;; but when words-include-escapes is set, that
                 ;; is not right and fixing it is boring.
                 (let ((lim (point)))
                   (backward-word 1)
                   (setq start (point))
                   (forward-word 1)
                   (setq end (min (point) lim)))
               (when (looking-back re (line-beginning-position))
                 (setq start (match-beginning 1))
                 (setq end   (match-end 1)))))
           ;; My extra check.  Check whether the enable function still works at
           ;; the start of the abbrev.
           (or (not enable-fun) (save-excursion (goto-char start) (funcall enable-fun)))
           ;; Then check to see if the word has an abbrev.  If it does record
           ;; the abbrev info.
           (setq name  (buffer-substring start end))
           (let ((abbrev (abbrev--symbol name table)))
             (when abbrev
               (setq enable-fun (abbrev-get abbrev :enable-function))
               (and (or (not enable-fun) (funcall enable-fun))
                    ;; This will also look it up in parent tables.
                    ;; This is not on purpose, but it seems harmless.
                    (list abbrev name start end))))))
    ;; Restore point.
    (goto-char pos)))
#+end_src

After I added this check I started mulling over what I had done and whether it
makes sense.  Do I need both checks?  Or should I take out the current check.

After thinking it over I have come to the conclusion that both checks are
necessary.  Checking the start of the abbrev to be expanded is, as mentioned,
for ensuring that an abbrev is not expanded outside of where you intend to
expand it.  But checking the current.  Consider the following hypothetical
example where cursor is at =^=.

#+begin_src emacs-lisp
(defun foo ()
  "Something args."
  ^)
#+end_src
