#+title: Generating Documentation
#+author: Luis Henriquez-Perez
# (assoc :url (package-desc-extras (cadr (assoc 'htmlize package-alist))))

Whenever I mention an emacs variable or function for the first time I will link
it to an html page containing its documentation.  The html page is generated
from an actual documentation buffer I use in emacs.  That is one of the best
ideas I have had for this blog.  Instead of just inferring what variables or
functions I mention do based on how I use them or what I say about them, readers
can actually see the official documentation for these functions in the exact
same way I can.  The only problem is that actually setting this up on my end for
me requires several steps.  I need to look the symbol up with [[/home/luis/Documents/blog/org/documentation/29.4-helpful--helpful-variable.html][helpful-variable]]
or, if it is a function or macro, [[/home/luis/Documents/blog/org/documentation/29.4-helpful--helpful-function.html][helpful-function]]; then I need to convert the
buffer to html using [[https://github.com/hniksic/emacs-htmlize][htmlize]]; and finally I need to save that htmlized buffer to
a file in my documentation folder.  That is quite the bit of work and something
I am not too keen on doing for every variable or function I happen to reference.
In this post I showcase how I automate this.  The idea is to write a function
that jumps to a particular link, determines if it refer to a variable or
function, takes an html "buffer snapshot" of its documentation, and saves it to
a file in the appropriate place.

One of the first things I am considering is how the "unfinished" link will look
like.  Obviously, I am not going to be changing all links, only a subset.  And I
need to be able to distinguish that subset from other links.  Moreover, I need
to know whether the symbol involved is a reference to a callable or a variable.
Ideally, I would use a snippet to expand into the link into but I do not want to
go there just yet so I am just going to say a link that looks like =[[][Vfoo]]=
means to look up foo as a variable; and one that looks like =[[][Ffoo]]= means to
look it up as a function.

The regexp will look something like this.  We want know the symbol in question
and whether it is a function or variable.

#+begin_src emacs-lisp
(rx "[[][" (group (or "V" "F")) (group (1+ (not "]"))) "]]")
;; => "\\[\\[]\\[\\([FV]\\)\\([^]]+\\)]]"
#+end_src

Then I need to check whether a file already exists.  A detail I did not mention
is that I am naming files based on the current version of emacs I am using.
This is to account for me using a different version of emacs later on.  In that
case I should not use the same documentation.

For simplicity and brevity I did not.

#+begin_src emacs-lisp
(cl-defun oo-next-doc ()
  "Jump to the next link."
  (interactive)
  (let (type symbol html-file help-fn help-buffer html-buffer doc-dir)
    (when (re-search-forward "\\[\\[]\\[\\([FV]\\)\\([^]]+\\)]]" nil t)
      (setq doc-dir (expand-file-name "../documentation"))
      (setq type (match-string 1))
      (setq symbol (intern (match-string 2)))
      (pcase type
        ("V"
         (setq html-file (expand-file-name (format "%s-helpful--%s.html" emacs-version symbol) doc-dir))
         (setq help-fn #'helpful-symbol)
         (unless (boundp symbol)
           (cl-return)))
        ("F"
         (setq html-file (expand-file-name (format "%s-helpful--%s.html" emacs-version symbol) doc-dir))
         (setq help-fn #'helpful-callable)
         (unless (fboundp symbol)
           (cl-return))))
      (replace-match (format "[[%s][%s]]" html-file symbol))
      (unless (file-exists-p html-file)
        (and (setq help-buffer (funcall help-fn symbol))
             (setq html-buffer (htmlize-buffer help-buffer))
             (progn (with-current-buffer html-buffer
                      (write-region (point-min) (point-max) html-file nil 'quiet))
                    (kill-buffer help-buffer)
                    (kill-buffer html-buffer)))))))
#+end_src
