#+title:how to get stuff on my index page
#+author:Luis Henriquez-Perez

The main thing I need to do is figure out how to get stuff on my index page that
is not just the list of blog posts sitemap.  This will be the front page of the
site so obviously I want things like my name, contact information, projects I
have done, etc.  In the manual I do not see.

Thomas Ingram has "extra stuff" on his index page via source blocks.  But if I
do that for my index page does not work.

# #+begin_src emacs-lisp
# #+end_src

He has stuff like this which I do not get.

# * Blog

# #+begin_blog-entries
# #+INCLUDE: "blog/index.org" :lines "3-"
# #+end_blog-entries

I see Dennis Ogbe's blog has a [[https://ogbe.net/blog/org_custom_sitemap][]]
that actually gives an example of a sitemap function.  I was hapy to see this
but I also do not want to necessarily generate the whole thing via elisp.  I did
like the way that Thomas Ingram did it and in the other website I see they also
have src blocks.

What is tough is that.

O.K. what I determined is that.
