#+title:on and off on evil collection
#+author:Luis Henriquez-Perez

I am between the fence with [[https://github.com/emacs-evil/evil-collection][evil-collection]].  Lots of famous people in the Emacs
community have said good things about it including [[][ambrevar]] and
[[][noctuid]].  The idea is to reduce efforts of creating bindings everywhere
for evil by creating a community maintained set of standard evil keybindings for
each Emacs application it is similar to [[https://github.com/emacscollective/no-littering][no-littering]] in this way.  My thinking
on it is that it is amazing when it does what you want but horrible when it does
what you do not want.  For example, I love its mapping of =i= used to enter
=evil-insert-state= to enter =wdired= in =dired= and =wgrep= in =grep=.  It is very clever
and it makes sense in the context of dired and grep buffers respectively.
However just today I did not like its decision to bind =gh= in =eww= to
[[file:/home/luis/Documents/MyBlog/org/documentation/29.4-helpful-callable--eww-list-histories.html][eww-list-histories]] because I had bound =gh= to [[file:/home/luis/Documents/MyBlog/org/documentation/29.4-helpful-callable--+evil-eval-operator.html][+evil-eval-operator]] and I wanted
that binding to be available everywhere.  So now I have to think about how to
make my keybindings take precedence over evil-collection keybindings in a clean
and nice way.  At first I thought it would be as simple as ensuring my bindings
happen after =evil-collection= keybindings.  But in this particular case that
would not work because more specific evil keybindings, in this case binding =gh=
in =eww-mode-map=, take precedence over more general keybindings, like binding
=gh= in the global-map.

I find it is keybinding for closing things, =ZZ=, a bit much.  O.K. it has parity
with vim but I wonder whether there is an easier to press binding than two
capital Zs even.  I do not know I cannot blame them for that I know it is
opinionated.

Ultimately I will continue to keep using =evil-collection= because the it helps me
more than it hurts me.  I rely heavily on it is [[https://github.com/magit/magit][magit]] and =dired= keybindings.
But eventually I want to structure my configuration so that my bindings take
precedent over evil-collection's.  I am not sure how of do that.  Actually even
this is not so simple because =evil-collection= keybindings are split up.  But
now I think.
