#+title: Diagnosing a Latency Problem
#+author: Luis Henriquez-Perez

Recently I started experiencing latency in emacs.  I could tell the typing and
the cursor movement felt slower.  Interestingly, the problem seemed to worsen
over time.  At first I thought it was my mode line but enabling and re-enabling
it had no effect.  Then I considered whether it was some mode I had enabled.
But I did not have any strange modes.  I did not even have the usual suspect,
text completion, enabled--other than =abbrev-mode= that is.  Suddenly, it hit me:
the log buffer.  A while back I started logging all sorts of events in my Emacs
configuration with [[https://github.com/Fuco1/emacs-lgr][lgr]].  The plan had been to enable logging all the time at
first just to make sure it worked; and afterwards only while =oo-debug-p= was
active.  Later, however, I changed my mind.  I thought it was not really costing
me anything to leave the log on.  On the contrary, it allowed me to quickly
identify bugs.  Therefore, I decided to just leave it on all the time.  The way
the logging worked was very simple: any message logged would simply write to a
buffer named =*log*=.  It is only now when considering my current performance
issue that I realize that the log buffer unlike the =*Message*= buffer has no cap.
It would just grow larger and larger.  And, I suspect, that at some point it
would get so large that it would slow everything down.  For now, I am disabling
logging when =oo-debug-p= is false.

#+begin_src emacs-lisp
(defmacro info! (msg &rest meta)
  (when oo-debug-p
    `(lgr-info oo-logger ,msg ,@meta)))

(defmacro error! (msg &rest meta)
  (when oo-debug-p
    `(lgr-error oo-error-logger ,msg ,@meta)))

(defmacro warn! (msg &rest meta)
  (when oo-debug-p
    `(lgr-warn oo-logger ,msg ,@meta)))

(defmacro fatal! (msg &rest meta)
  (when oo-debug-p
    `(lgr-fatal oo-logger ,msg ,@meta)))

(defmacro trace! (msg &rest meta)
  (when oo-debug-p
    `(lgr-trace oo-logger ,msg ,@meta)))

(defmacro debug! (msg &rest meta)
  (when oo-debug-p
    `(lgr-debug oo-logger ,msg ,@meta)))
#+end_src

In spite than this performance hiccup, logging has been so useful for me that I
would like to make it toggleable.  Instead of this "band-aid" solution I would
like store the logs internally list and with some cap.  With this list I can
then write the logs to a buffer when I want to see it.
