#+TITLE: company completion
#+AUTHOR: Luis Henriquez-Perez

I had used company previously many years ago.  Then for a long time I have not
used any completion system.  Now I want to provide the first impressions of the
company right now.

* basic settings

First I set basic settings.

See [[https://www.monolune.com/articles/configuring-company-mode-in-emacs/][]]

#+begin_src emacs-lisp
(hook! prog-mode-hook company-mode)
#+end_src

#+begin_src emacs-lisp
(opt! company-minimum-prefix-length 1)
#+end_src

There are too many backends enabled for org.  Backends 

* simplifying complexity

The first thing you see when checking the company backends is a long list of who
knows what.  For sure you do not need all this stuff at least in the org buffer
I am using.  To get a handle on the package I first tested in the org buffer
used to run this post how many packages.

#+begin_src emacs-lisp
(company-bbdb company-semantic company-cmake company-capf company-clang company-files
              (company-dabbrev-code company-gtags company-etags company-keywords)
              company-oddmuse company-dabbrev)
#+end_src

To get a handle on things, I just set it to one.

#+begin_src emacs-lisp
(setq-local company-backends '(company-capf))
#+end_src

* company unexpected behavior when typing

I encountered some kind of small unpredicatable behavior.  For example, when
beginning to type =v= I would get the proper suggestions: "Vivamus", "Volutpat",
"velit" and "vitae" but then if I choose to type "e" for the intention of
getting "velit" the popup would go away.  Instead I expected the the inline
preview to show (insce the choices should narrow down to one) until I finished
typing "velit".  For some reason company popup quits even when typing the same
characters as one of the candidates.

In contrast, corfu acts much more predictably.  Essentially, it did exactly what
I expected it to do all the time.

* adding text

I added this latin text from [[https://github.com/jschaf/emacs-lorem-ipsum][lorem-ipsum]] so I would have words in the buffer I
could try to match with =dabbrev=.  Volutpat eleifend.  v

Aliquam erat volutpat.  Nunc eleifend leo vitae magna.  In id erat non orci
commodo lobortis.  Proin neque massa, cursus ut, gravida ut, lobortis eget,
lacus.  Sed diam.  Praesent fermentum tempor tellus.  Nullam tempus.  Mauris ac
felis vel velit tristique imperdiet.  Donec at pede.  Etiam vel neque nec dui
dignissim bibendum.  Vivamus id enim.  Phasellus neque orci, porta a, aliquet
quis, semper a, massa.  Phasellus purus.  Pellentesque tristique imperdiet
tortor.  Nam euismod tellus id erat.  Vivamus imperdiet.  Praesent
tristique. gravida lobortis fermentum.

* ensure to check only current buffer

I have noticed it is very easy to make company slow, much easier than corfu.
Just playing around with it and using essentially out of the box I ran into
noticeable delays in emacs-lisp buffers.  I have been trying to see if I can get
predictable resuts from both corfu and company.  I am surprised that cape has a
separate setting for checking other buffers.

With these settings I got essentially.  I got both company and corfu to
behave predictably in the current buffer.  volutpat

#+begin_src emacs-lisp
(opt! dabbrev-check-all-buffers nil)
(opt! dabbrev-check-other-buffers nil)
(opt! cape-dabbrev-check-other-buffers nil)
#+end_src

* isolate a backend

#+begin_src emacs-lisp
(add-hook 'completion-at-point-functions #'cape-dabbrev nil 'local)
(remove-hook 'completion-at-point-functions #'pcomplete-completions-at-point 'local)
#+end_src

* escaping with evil

I have this function bound to escape.  I have to rethink the function.  I think
it can be better done with a hook, specifically one that is run by
[[file:/home/luis/Documents/MyBlog/org/documentation/29.4-helpful-callable--run-hook-with-args-until-success.html][run-hook-with-args-until-success]].  Vivamus pellentesque Vivamus Pellentesque
pell.

#+begin_src emacs-lisp
(defun oo-dwim-escape ()
  "Exits out of whatever is happening after escape."
  (interactive)
  (when (bound-and-true-p evil-mode)
    (evil-normal-state 1))
  (cond ((minibuffer-window-active-p (minibuffer-window))
		 (if (or defining-kbd-macro executing-kbd-macro)
			 (minibuffer-keyboard-quit)
           (abort-recursive-edit)))
		((or defining-kbd-macro executing-kbd-macro) nil)
        (t
         (when (and (not buffer-read-only)
                    (buffer-file-name)
                    (buffer-modified-p))
           (save-buffer))
		 (keyboard-quit))))
#+end_src

* I was thnking I was getting bugs because of 

#+begin_src emacs-lisp
(setq package-pinned-packages '((company . "melpa-stable") (org . "melpa-stable")))
#+end_src

I do not know if it is just me but isolate but I tell you I was getting tons of
bugs from company.  I could not get it to do this simple thing.  When I
restarted my configuration and tried company again and changed the settings to
the following it worked well.  I am thinking of whether to use company as a
helper.  Though I would like a function that excludes
