#+title:Screenshot Function
#+author: Luis Henriquez-Perez

I have always had the goal of being able to document something at the speed of
thought. I want something to take a screenshot.  Specifically, I want functions
for window, region and full screen screenshots.  It is something that is
particularly important for things like this blog but also just generally
important for documenting information that is better described with a picture.
I have written a function to do this but I could not find it.  I decided to
compromise and use an external package I have known about called [[https://github.com/Luis-Henriquez-Perez/escr][escr]].  It is
the only package I could find that could do window, region and frame
screenshots for Emacs.

I install it via =package.el= in [[file:../documentation/29.4-110-init-package.html][110-init-package.el]].

This is my configuration for it, its [[file:../documentation/29.4-130-init-escr.html][130-init-escr.el]].  I do not do much.  I
just declare and autoload the main =escr= commands and set the directory where
screenshots will go.

#+begin_src emacs-lisp
(require '050-base)

(opt! escr-screenshot-directory (expand-file-name "~/Pictures"))

(declare-function escr-region-screenshot "escr")
(declare-function escr-window-screenshot "escr")
(declare-function escr-frame-screenshot "escr")

(autoload #'escr-region-screenshot "escr" nil t 'function)
(autoload #'escr-window-screenshot "escr" nil t 'function)
(autoload #'escr-frame-screenshot "escr" nil t 'function)
#+end_src

Of course, I also added keybindings for these function.

#+begin_src emacs-lisp
(bind! oo-app-map "s r" #'escr-region-screenshot)
(bind! oo-app-map "s f" #'escr-frame-screenshot)
(bind! oo-app-map "s w" #'escr-window-screenshot)
#+end_src
