#+title: Little Changes
#+author: Luis Henriquez-Perez

* excluding files

I do not want to include every file into my blog.  The way I work at least is
that I always have many unfinished posts, drafts if you will.  I do not want
these drafts to be accidentally added to the sitemap and the blog.  I also
preferably did not want to add more complexity to the directory structure of the
blog to create an entirely different directory for these drafts.  In the end I
decided to prepend blog post didntames with =drafts_=.

#+begin_src emacs-lisp
(setq org-publish-project-alist
      `(("posts"
         :base-directory "org/"
         :base-extension "org"
         :publishing-directory "html/"
         ;; Ignore files that start with `draft_'.
         :exclude "draft_.+\\.org$"
         ...)
        ...))
#+end_src

* auto adding and generating my links

From [[https://diego.codes/post/blogging-with-org/][]]

#+begin_src emacs-lisp
(defun filter-local-links (link backend info)
  "Filter that converts all the /index.html links to /"
  (if (org-export-derived-backend-p backend 'html)
	  (replace-regexp-in-string "/index.html" "/" link)))

;; Do not forget to add the function to the list!
(add-to-list 'org-export-filter-link-functions 'filter-local-links)
#+end_source

[[http://www-public.telecom-sudparis.eu/~berger_o/blog/blogging-with-org-mode-for-good.html][]]

[[https://taingram.org/blog/org-mode-blog.html][]]

* Nicolas Petton's Website

This is the main thing I gleaned from Petton's webiste.  Oh and he really should
change the color theme of the code in his homepage.  It is so unreadable.  My
guess is that he exported his website while unthinkingly using a dark theme.  He
did not check the output.  And his code came out white on white.

#+begin_src emacs-lisp
(defvar nico-website-html-head
  "<link href='http://fonts.googleapis.com/css?family=Libre+Baskerville:400,400italic' rel='stylesheet' type='text/css'>
<link rel='stylesheet' href='css/site.css' type='text/css'/>")

(defvar nico-website-html-blog-head
  "<link href='http://fonts.googleapis.com/css?family=Libre+Baskerville:400,400italic' rel='stylesheet' type='text/css'>
<link rel='stylesheet' href='../css/site.css' type='text/css'/>")

(defvar nico-website-html-preamble 
  "<div class='nav'>
<ul>
<li><a href='/'>Home</a></li>
<li><a href='/blog/index.html'>Blog</a></li>
<li><a href='http://github.com/NicolasPetton'>GitHub</a></li>
<li><a href='http://twitter.com/NicolasPetton'>Twitter</a></li>
<li><a href='/contact.html'>Contact</a></li>
</ul>
</div>")
#+end_src
