#+title:experience using emms
#+author:Luis Henriquez-Perez

** background

One of the things I have always found as a problem is staying awake when sitting
for a long period of time.  I know several people do it by frequently drinking
coffee, likely for the caffeine it provides.  However, I do not want to develop a
dependence or tolerance of caffeine or any other drug for that matter.  And so I
have been looking into natural ways to stay awake.  One of these is to just
listen to music.  This got me back into using [[https://www.gnu.org/software/emms/][emms]], a multimedia player for
Emacs.

** setup

I followed its manual page and added the music from my music directory with
[[file:/home/luis/Documents/MyBlog/org/documentation/29.4-helpful-callable--emms-add-directory.html][emms-add-directory]][fn::Technically in the manual [[file:/home/luis/Documents/MyBlog/org/documentation/29.4-helpful-callable--emms-add-directory-tree.html][emms-add-directory-tree]] was
used, but no big deal.].  Although it is possible to do it interactively, I
choose to do it via eshell.

#+begin_src sh
/m/h/a/Music λ (emms-add-directory (eshell/pwd))
#+end_src

# ** trouble opening emms browser

# I am having a hard time getting emms to display the tracks in the emms browser.
# I already have added songs to emms with [[file:/home/luis/Documents/MyBlog/org/documentation/29.4-helpful-callable--emms-add-directory-tree.html][emms-add-directory-tree]] as recommended
# by the manual but when I invoke [[file:/home/luis/Documents/MyBlog/org/documentation/29.4-helpful-callable--emms-browser.html][emms-browser]] it says that no songs are cached
# and to add them with =emms-add-directory-tree=.  So confusingly songs are
# registered fine with the emms player buffer but not with emms browser.

# #+begin_src emacs-lisp
# (setq emms-info-functions '(emms-info-native))
# #+end_src

# I had moved all of my music to an external drive.  The directory with my music
# contained.  My preliminary conclusion is that the tracks do not have author
# information so nothing is happening.

** track keeps repeating in playlist

I had the impression when a track in the playlist finishes the next track
starts.  And the manual seems to agree with me when it says that: that "Emms
[should]" proceed "to play the media tracks in the buffer from top to bottom
until the end of the playlist".  Instead emms just repeats the current
track forever.  I even checked if the setting for repeating the same track,
[[file:/home/luis/Documents/MyBlog/org/documentation/29.4-helpful-variable--emms-repeat-track.html][emms-repeat-track]], is disabled; and it was.

According to [[https://old.reddit.com/r/emacs/comments/y0mblz/why_does_emms_not_play_the_next_track/][this reddit post]] this happens because of the default configuration
of the specific player.  To fix this for mpv you specify the =--no-config= flag
for the emms command via [[file:/home/luis/Documents/MyBlog/org/documentation/29.4-helpful-variable--emms-player-mpv-parameters.html][emms-player-mpv-parameters]].  In the posts many other
flags were also added which I (maybe irrationally) just copied as well.

#+begin_src emacs-lisp
(setopt emms-player-list '(emms-player-mpv))
(setopt emms-player-mpv-parameters (list "--quiet"
                                         "--really-quiet"
                                         "--no-config"
                                         "--no-audio-display"
                                         "--force-window=no"
                                         "--vo=null"))
#+end_src

** invisible emms buffer

The emms buffer is invisible.  Despite being mentioned in the documentation, it
was still surprising to me.  I expected to be able to access it with
[[file:/home/luis/Documents/MyBlog/org/documentation/29.4-helpful-callable--switch-to-buffer.html][switch-to-buffer]] but instead had to exclusively use [[file:/home/luis/Documents/MyBlog/org/documentation/29.4-helpful-callable--emms-playlist-mode-go.html][emms-playlist-mode-go]].
This happens because the default [[file:/home/luis/Documents/MyBlog/org/documentation/29.4-helpful-variable--emms-playlist-buffer-name.html][emms-playlist-buffer-name]] is set to a buffer
whose name starts with a space, " EMMS Playlist" making it "invisible".  I
forgot about being able to do this in Emacs.  The easy fix is to just rename it
to the same thing but without the initial space.

#+begin_src emacs-lisp
(setopt emms-playlist-buffer-name "*EMMS Playlist*")
#+end_src

** playing random songs

I like playing random songs but I do not necessarily like using [[file:/home/luis/Documents/MyBlog/org/documentation/29.4-helpful-callable--emms-random.html][emms-random]]
which moves point to a random track in the playlist.  The thing is I prefer no
repeats and using =emms-random= can result jumping to the same track again.
Instead, a clever way of achieving the same result is to use [[file:/home/luis/Documents/MyBlog/org/documentation/29.4-helpful-callable--emms-shuffle.html][emms-shuffle]] and to
just go down the songs one by one.

# ** potential of saving playlists with text files

# I also want to comment on the potential on saving playlists as text files.  It
# is cool that you can potentially filter the playlist via [[][marking]] and save
# the subset of tracks you want for a particular playlist.

** general configuring of Emacs packages

This experience is telling about generally configuring Emacs packages.  Very
often compared to apps in real life Emacs packages might have a less "refined"
out of the box experience.  And you will encounter things you do not expect,
sometimes with even basic functionality even after following the manual.  More
often than not the package does work but some time needs to be invested to
understand it.
