#+title:no applicable method magit
#+author:Luis Henriquez-Perez

I now am getting the following unusual error when I try to see the magit log
view.  To be specific this is when I invoke [[file:/home/luis/Documents/MyBlog/org/documentation/29.4-helpful-callable--magit-log.html][magit-log]].

#+begin_src text 
transient-setup: No applicable method: transient-format, #s(transient-subgroups #s(transient-column nil 1 nil nil nil nil nil nil nil ...) 1 nil nil nil nil nil nil nil ...)
#+end_src

No idea what it is.  It is not uncommon to get errors like this with packages.
My first instinct is to uninstall magit and its dependencies, pin magit to be
installed with melpa-stable and then install it again.  I had left the
bleeding-edge variant of magit because I never had any problems with it before.

One thing though I do not know how to remove a package together with its
dependencies.  I looked through some package.el functions such as
[[file:/home/luis/Documents/MyBlog/org/documentation/29.4-helpful-callable--package-autoremove.html][package-autoremove]] which I do not understand.

Honestly, this makes me want to just switch to elpaca.  One of the big reasons
of using elpaca is to avoid these random errors occurring because
of some unstable package version.

This is probably imprecise but to get rid of the problem I invoked
[[file:/home/luis/Documents/MyBlog/org/documentation/29.4-helpful-callable--package-delete.html][package-delete]] on magit, pinned magit to magit to melpa-stable and reinstalled
it.  I did not deal with it is dependencies and indeed when I look at the
strings it seems like the dependencies like [[https://github.com/magit/transient][transient]] are still at the latest
version.

#+begin_src emacs-lisp
(setq package-pinned-packages '((magit . "melpa-stable") (org . "melpa-stable")))
#+end_src

I think we are seeing a trend here.  Big packages that are updated frequently
should generally be installed from melpa-stable.
