#+title:explaining my publish alist
#+author:Luis Henriquez-Perez

Most of the configuring for org-publish happens in =org-public-project-alist=, with
each element being a publishing project.  Today I worked on refining and fixing
the [[file:/home/luis/Documents/MyBlog/org/documentation/29.4-helpful-variable--org-publish-project-alist.html][org-publish-project-alist]].  And here I will explain the reasoning behind my
tinkering project by project.

The "index" project includes just one file, the index file.  The reason it is in
a separate project is partly because unlike every other page on my website I do
not want =org-publish= it to give it a default title (I want the title, my name,
to be a link to the about page) and partly because

# #+caption: the "index" project consisting of the single index.org
#+begin_src emacs-lisp
("index"
 :base-directory "org"
 :base-extension "org"
 :exclude ".*"
 :include ("index.org")
 :recursive nil
 :publishing-directory "html"
 :publishing-function org-html-publish-to-html
 :with-title nil
 ,@oo-publish-defaults)
#+end_src

the index file includes the sitemap file generated by the "posts" project (below
is code that includes it) meaning that the "posts" project needs to be published
beforehand.

# #+caption: text in index.org that includes sitemap.org
#+begin_src org
,#+begin_blog-entries
,#+INCLUDE: "posts/sitemap.org" :lines "3-"
,#+end_blog-entries
#+end_src

Specifically, I publish the "posts" project first so that the sitemap file is
created before the index project is published.  And that is why I use the more
fine-grained [[file:/home/luis/Documents/MyBlog/org/documentation/29.4-helpful-callable--org-publish.html][org-publish]] instead of the more generic [[file:/home/luis/Documents/MyBlog/org/documentation/29.4-helpful-callable--org-publish-all.html][org-publish-all]].

#+begin_src emacs-lisp
(org-publish "posts" :force)
(org-publish "pages" :force)
(org-publish "static" :force)
(org-publish "index" :force)
#+end_src

The "pages" project is for publishing non-post files of the website; things
like my [[file:../about.org][about page]] and my [[file:../index.org][index page]].

#+begin_src emacs-lisp
("pages"
 :base-directory "org"
 :base-extension "org"
 :publishing-directory "html"
 :recursive nil
 :exclude "index\\.org$"
 :publishing-function org-html-publish-to-html
 ,@oo-publish-defaults)
#+end_src

The "posts" project is, as its name suggests, for blog posts.  I ignore any
posts prepended with drafts so I can have control over which posts are published
at any given time.  Initially, I had the pages and the posts together as one
project but since posts have their own CSS stylesheet and I only want the
sitemap for blog posts it seemed logical to put them as separate projects.
Right now the stylesheet for the blog posts is in the previous directory (the
one that corresponds to the "pages" project).  It might be more logical to also
add it to the post directory but I have not decided yet.

#+begin_src emacs-lisp
("posts"
 :base-directory "org/posts"
 :base-extension "org"
 :publishing-directory "html/posts"
 :recursive nil
 :exclude "sitemap\\.org$\\|draft_.+\\.org$"
 :publishing-function org-html-publish-to-html
 :auto-sitemap t
 :sitemap-filename "sitemap.org"
 :html-head "<link rel=\"stylesheet\" href=\"../style.css\" type=\"text/css\"/>"
 :sitemap-sort-files anti-chronologically
 ,@oo-publish-defaults)
#+end_src

The "static" project, also aptly named, contains are files that are
"static", meaning that they do not change and will be published as is.  This is
for virtually anything that is not an =.org= file.

#+begin_src emacs-lisp
("static"
 :base-directory "org"
 :base-extension "css\\|js\\|png\\|jpg\\|gif\\|pdf\\|mp3\\|ogg\\|swf\\|php\\|mov\\|html\\|txt\\|"
 :publishing-directory "html/"
 :publishing-function org-publish-attachment
 :recursive t)
#+end_src
