#+title:confusions when using emms
#+author:Luis Henriquez-Perez

One of the things I have always found as a problem is staying up when sedentary
for a long period of time.  I know several people, particularly programmers, do
it by frequently drinking coffee likely for the caffeine it provides.  I do not
want to develop a dependence or tolerance of caffeine.  And so I have been
looking into natural ways to stay awake.  One of these is to just listen to
music.  This got me back into trying [[https://www.gnu.org/software/emms/][emms]].

I followed its manual page and added a directory with and used.  Since I do not
have any subdirectories in my music directory I choose to simply.
When I added my directory via eshell it worked for [[file:/home/luis/Documents/MyBlog/org/documentation/29.4-helpful-callable--emms-playlist-mode-go.html][emms-playlist-mode-go]] but
[[file:/home/luis/Documents/MyBlog/org/documentation/29.4-helpful-callable--emms-browser.html][emms-browser]] did not do anything.  It is possible to do it interactively though
I choose to do it via eshell.

#+begin_src sh
/m/h/a/Music λ (emms-add-directory (eshell/pwd))
#+end_src

I am having a hard time getting emms to display the tracks in the emms browser.
I already have added songs to emms with [[file:/home/luis/Documents/MyBlog/org/documentation/29.4-helpful-callable--emms-add-directory-tree.html][emms-add-directory-tree]] but when I
invoke [[file:/home/luis/Documents/MyBlog/org/documentation/29.4-helpful-callable--emms-browser.html][emms-browser]] it says that no songs are cached and to add them with
=emms-add-directory-tree=.  It looks like.

#+begin_src emacs-lisp
#+end_src

I had moved all of my music to an external drive.  The directory with my music
contained.  My preliminary conclusion is that the tracks do not have author
information so nothing is happening.

#+begin_src emacs-lisp
#+end_src

Another confusion is what happens when a track in the playlist finishes.  I
thought it would autmatically go to the next track but it seems to just repeat
the current track forever.  I have repeating the same track, [[file:/home/luis/Documents/MyBlog/org/documentation/29.4-helpful-variable--emms-repeat-track.html][emms-repeat-track]],
disabled.

Another annoyance is that the emms buffer is invisible for some reason.  So I
need to invoke =emms-playlist-mode-go= to access it instead of =switch-to-buffer=.
