#+TITLE: tricks I learned to make using tempel smoother
#+AUTHOR: Luis Henriquez-Perez

Having gotten to a more stable state with my Emacs configuration, I have been
focused less on file naming and more on enhancing areas that I have neglected.
One of these is text completion or as Emacs calls it "auto-typing".  In the
process of grokking tempel to my liking I have accrued several useful settings
which I share here.

* make =tempel-map= an overriding map

Frustratingly when I first began using tempel the keybindings to =tempel-map= in
=evil-insert-state= were not working.  That is because default evil bindings still
took precedence over.  To tell evil to make those keybindings precedence we need
to make =tempel-map= an intercept map.

#+begin_src emacs-lisp
(eval-after-load 'tempel
  '(eval-after-load 'evil
     (evil-make-overriding-map tempel-map)))
#+end_src

* ensure insert state after inserting a template

You can be just about certain you will be typing text just after inserting a
tempel template because there will be fields you have to fill out.  That is why
I recommend advising [[file:/home/luis/Documents/MyBlog/org/documentation/29.4-helpful-callable--tempel-insert.html][tempel-insert]] to enter insert state after it is done.  In
general, configuring functions to enter insert state is so common that I
recommend you create a dedicated function for this.

#+begin_src emacs-lisp
(setq-local completion-at-point-functions '(cape-dabbrev t))
(defun oo--enter-evil-insert-state-maybe (&rest _)
  "Enter insert state if `evil-mode' is enabled."
  (when (bound-and-true-p evil-mode)
    (evil-insert-state 1)))

(advice-add 'tempel-insert :after #'oo--enter-evil-insert-state-maybe)
#+end_src

* properly use map an abbrev to a tempel expansion

First let me mention the solution that tempel provides: [[file:/home/luis/Documents/MyBlog/org/documentation/29.4-helpful-callable--tempel-abbrev-mode.html][tempel-abbrev-mode]].
That mode defines abbrevs for every named template, puts them in an abbrev
table.  This solution is too crude and opinionated for my taste.  It assumes
that you want the abbrevs to be the same name you defined for your tempel
templates.  And it decides how to set up the abbrev table.  This is designed for
someone who just wants something working fast.

If you are not in a rush.  What I recommend is just doing it explicitly with good
old [[file:/home/luis/Documents/MyBlog/org/documentation/29.4-helpful-callable--define-abbrev.html][define-abbrev]].  Specify the circumstances when an abbrev should be active in
the =:enable-function= property.

#+begin_src emacs-lisp
(defun oo-expand-elisp-defun ()
  (interactive)
  (tempel-insert '"(defun " p " (" p ")" n> "\"" p "\"" n> r ")")
  ;; This is important, the will still be inserted despite having added the
  ;; `no-self-insert' property if this function does not return a non-nil value.
  ;; Note `tempel-insert' returns nil.  I learned this the hard-way.
  t)

(put 'oo-expand-elisp-defun 'no-self-insert t)

(define-abbrev global-abbrev-table "dfn" "" #'oo-expand-elisp-defun :enable-function #'oo-in-elisp-mode-p)
#+end_src

* simplify creating templates with a macro

Make a macro similar to [[file:/home/luis/Documents/MyBlog/org/documentation/29.4-helpful-callable--define-skeleton.html][define-skeleton]].  When I dabbled with [[][skeletons]] I
became quite endeard to the =define-skeleton= macro.  It was simple but made
things much more convenient.

#+begin_src emacs-lisp
(defmacro deftempel! (name &rest body)
  "Define a tempel template."
  (declare (doc-string 2) (indent defun))
  (setq documentation (when (stringp (car body)) (list (pop body))))
  `(progn (defun ,name ()
            ,@documentation
            (interactive)
            (tempel-insert ',body)
            t)
          (put ',name 'no-self-insert t)
          ',name))
#+end_src

* remember to use the region

Remember to use the =r= element.  This makes it so that when a region is active
when you invoke the command it will wrap the snippet around the region.  Only
bad thing is that the snippet assumes your done writing the snippet.  As in afte
the region but I would prefer the cursor still in the snippet.

#+begin_src emacs-lisp
(deftempel! oo-expand-to-defun
  "Expand to defun."
  "(defun " p " (" p ")" n> "\"" p "\"" n> r ")")
#+end_src
