#+title:switching to html
#+author:Luis Henriquez-Perez

For a long time I vacillated between using org or writing my blog in pure HTML,
CSS, and maybe some JavaScript.  As of writing this, my blog is in org.  And do
not get me wrong, org has its advantages, but I do not like how I have to figure
out how to do things that would be straight-forward with CSS and HTML all the
time.  At the same time I feel like I am too deep in to back out now.  Here I
will discuss factors that I am weighing to decide what to do.

** readability

Org is much more readable and less cluttered than HTML.  It might be considered
syntax heavy among markup languages, but it is feather-light compared with HTML.
This is an advantage because you can focus on what is important for blog post,
the actual content.  In contrast when working with HTML your vision is rife with
a plethora of tags.  I have trouble getting some of them to indent properly or
even getting the indentation just the way I want despite using [[https://www.html-tidy.org/][html-prettify]].
To make matters worse unlike org HTML lacks support for hiding links making
sentences with links long and unreadable.  For a simple website, like this blog,
it is definitely nice writing posts.

** source blocks

With HTML to add sample code snippets to your webpage you add the in =pre= and
=code= tags and for syntax highlighting you use something like [[https://prismjs.com/][prism.js]].  It is
not at all perfect because you have to rely that the external JavaScript first
has your language.  For example, just looking at the supported languages I can
already tell emacs-lisp is not supported, and neither is it is relative
common-lisp.  So already at best my syntax highlighting will be different than.
And considering it from a more abstract design perspective it really is a waste
because I am using some external thing to try to replicate what I already have
in Emacs syntax highlighting.

One solution described by xah lee is to write [[https://github.com/hniksic/emacs-htmlize][htmlize]].  And while this works
and correctly captures the syntax highlighting of your Emacs configuration.  The
problem is the text is a completely unreadable blob of span tags.  Imagine
editing that garbage.  See for yourself.

This is the source code you would see in an emacs-lisp source block.  And as you
can see it would look exactly the same as regular source code.

#+begin_src emacs-lisp
(defun oo-in-blog-post-p ()
  "Return non-nil if the current buffer is for one of my blog posts."
  (declare (pure t) (side-effect-free error-free))
  (and (derived-mode-p 'org-mode)
       (stringp default-directory)
       (string= (expand-file-name default-directory)
                (expand-file-name "~/Documents/MyBlog/org/posts/"))))
#+end_src

And this is what you would see in an HTML of the same code, a completely
uneditable mess.  If you wanted to edit it you would need to convert it back to
source code and then reconvert it to HTML.  And of course even if you did that
you would likely struggle edit the code properly because the major mode of the
buffer it is in will be mhtml-mode or web-mode, not emacs-lisp.  So in addition
to this you would have to configure something like polymode or mmm-mode.  It is
such a pain.  Not to mention, forget about indenting this properly.  The spacing
is extremely fragile because any little change will affect.

#+begin_src mhtml
<div class="org-src-container">
<pre class="src src-emacs-lisp"><code>(<span style="font-weight: bold;">defun</span> <span style="font-weight: bold;">oo-in-blog-post-p</span> ()</code>
<code>  <span style="font-style: italic;">"Return non-nil if the current buffer is for one of my blog posts."</span></code>
<code>  (<span style="font-weight: bold;">declare</span> (pure t) (side-effect-free error-free))</code>
<code>  (<span style="font-weight: bold;">and</span> (derived-mode-p <span style="font-weight: bold;">'</span><span style="font-weight: bold; text-decoration: underline;">org-mode</span>)</code>
<code>       (stringp default-directory)</code>
<code>       (string= (expand-file-name default-directory)</code>
<code>                (expand-file-name <span style="font-style: italic;">"~/Documents/MyBlog/org/posts/"</span>))))</code>
</pre>
</div>
#+end_src

Both of these would produce the same HTML so they are the same in terms of
output.  But it is obviously really nice to have hurman readable code as visible
to you as you write our blog.

Org handles source blocks way better and with elegance.  But you have the power
to see the source code as it its.  Org mode acts as something of a multi-mode
like [[https://github.com/dgutov/mmm-mode][mmm-mode]] or [[https://github.com/polymode/polymode][polymode]] where you can see the source code as it is and edit
it.  It is so nice compared with the aforementioned alternative.

** easy and predictable to change

When there is a change you need to make to the site, it is much easier to reason
about how to make that change with HTML and CSS than to do so indirectly with
=org-publish=.  The thing is that =org-publish= adds another layer of complexity to
your website.  Not only do you have to know HTML and CSS, but you also need to
understand.  For this reason alone I am considering switching to pure html and
css, simply because I want full control.  As in when I have an unexpected change
I need to make I want it to be able to be made in a predictable way.  I will
give an example.  I am trying to.

* how to slowly migrate

How to slowly migrate to org and css.  I do want to take advantage of org.
