After you have installed your packages for the first time with elpaca you are
all good.  But installing them is where the rub is.

One issue is garbage collection. 

When elpaca is installing many packages my computer slows down then freezes.
Twice I have had to restart my computer because of this freezing.  This also
happened with package.el until I started garbage collecting between package
installs.  I do not know if this will help for elpaca because it uses external
processes for building and setting up packages so in theory it is not accruing
so much garbage.  I tried installing packages while leaving my garbage
collection with its default value to no avail.

These are the steps I plan to take.

* add a command switch to Emacs =--install-only=

This switch will signify to Emacs that it should only install external packages
and not load the rest of the configuration.  Maybe I will make it so after
everything has been processed Emacs will restart itself and everything will
work.

So one thing I did was add a command for starting Emacs when I am installing
several packages.  I did that via adding.  Although not what I would call best
practice.  Simulating Emacs startup by running =after-init-hook= and
=emacs-startup-hook= works surprisingly well.  One thing I noticed is that
=initial-buffer-choice= also missed timing.

I was thinking of just switching startup to this.  The benefit being that I do
not have to manage two different startup methods and that this one should work
both times?  Not sure actually.

I also need to inspect elpaca functions to find one that will tell me if there
are things in the queue and how many.  I want to know if there are any packages
that need to be installed on startup.  Specifically, I want to know if there are
some or none.  If there are none then I just go about my config normally, but if
there are some then I do this.  I do not know.  So is the
=elpaca-after-init-hook= always run, even if no packages were installed?  That is
my understanding.  I think the way it will have to work is during the
elpaca-after-init-hook I change what I do based on if I have missed timing in
calling the hooks.  I check =after-init-time= and if that has been done then I
know I need to run =after-init-hook= and =Emacs-startup-hook= myself.  Otherwise, I
do not have to do anything and let startup proceed normally.

#+begin_src emacs-lisp
(if oo-install-external-packages-p
    (progn (message "INSTALLING EXTERNAL PACKAGES")
           (require! :to 111)
           (add-hook 'after-init-hook #'elpaca-process-queues)
           (add-hook 'emacs-startup-hook (lambda () (setq gc-cons-threshold 800000)))
           (add-hook 'elpaca-after-init-hook (lambda ()
                                               (require! :from 111)
                                               (when after-init-time
                                                 (run-hooks 'after-init-hook 'emacs-startup-hook)))))
  (require! :profile t))
#+end_src 

Although this is recommended in the elpaca wiki, do not do if like me you
attempt to create a setup that will.  It can get tricky to add into
`after-init-hook' from outside the hook.

#+begin_src emacs-lisp
(add-hook 'after-init-hook #'elpaca-process-queues)
#+end_src

* consistent setup

One thing I want from =elpaca= is a consistent starting setup that does not freeze
or slow down my computer.  Thus far I have had problems with all of these
things.  By consistent I mean that given no change in my configuration and given
that on my first Emacs run, all my packages were installed in one go, if I were
to delete the package directory and restart Emacs with a lockfile then all my
packages should install the same way without problems.  I should not have to
restart my Emacs multiple times to finish installing all the packages because
the install of some failed.  I have also experienced freezing with my computer.
Now I will say I have very old computers.  One is a desktop, a mac I bought
refurbished near 2012.  One is a laptop.  When I have used elpaca the cpu
consumption of Emacs would go up, sometimes to 100% of my cpu.  I tried to limit
the number of processes done at once hoping that I could reduce the system load
even at the cost of a longer startup time (I am willing to sacrifice speed for
consistency) but when I did this sometimes the packages.  I add the hook to
Emacs Emacs- Emacs Emacs Emacs- Emacs- Emacs+ Emacs Emacs- Emacs Emacs- emacs
emacs for your information emacs Emacs- Emacs Emacs Emacs Emacs for your
information- Emacs.  emacs-startup-hook aih.  after-init-hook

