#+title:abbrev file or not
#+author:Luis Henriquez-Perez

I have already written well over 1600 abbrevs specifically catered to my writing
and preferences.  Naturally, I want to reuse these abbrevs wherever I go.  Right
now I version control these abbrevs, and eschew existing Emacs functionality to
manage them myself, keeping them in [[../documentation/29.4-999-abbrevs.html][999-abbrevs.el]].  But I
cannot shake the lingering thought that maybe I should let just Emacs manage it
with its existing facilities instead.  Emacs saves your abbrev file as specified
by [[file:/home/luis/Documents/MyBlog/org/documentation/29.4-helpful-variable--abbrev-file-name.html][abbrev-file-name]] via [[file:/home/luis/Documents/MyBlog/org/documentation/29.4-helpful-callable--write-abbrev-file.html][write-abbrev-file]] .  You might be wondering why.  The
reason was to be consistent with my other lisp files.

I have decided I am going to try keeping my abbrev file in one.  Another benefit
I the all my abbrevs would go into into just one file.  I could simplify my
configuration from having two files to just one.

Emacs already does it for you so I have an incentive to use existing resources
instead of reinventing the wheel.  Emacs already has functions for adding
abbrevs such as [[file:/home/luis/Documents/MyBlog/org/documentation/29.4-helpful-callable--add-global-abbrev.html][add-global-abbrev]] and [[file:/home/luis/Documents/MyBlog/org/documentation/29.4-helpful-callable--inverse-add-global-abbrev.html][inverse-add-global-abbrev]] that I would
essentially need to reimplement if I did not use Emacs abbrev file saving
support.  On the one hand, the existing functions do not do exacly what I want
to do.  For example, =add-global-abbrev= does not provide a way to specify the
[[][:enable-function]] property which I use heavily.  Additionally I am not
happy with the way that it is actually mentioned in another post that.  Also
these are not hard functions to write and I have already done most of the
preliminary work when I writing [[file:/home/luis/Documents/MyBlog/org/documentation/29.4-helpful-callable--oo-dwim-add-abbrev.html][oo-dwim-add-abbrev]].

Another consideration is that Emacs tracks the count of the abbrevs which is
information I might be interested in but it also means that there is going to be
constant commits to this abbrev file all the time.  I mean there already are
frequent commits because I add abbrevs all the time but I imagine there would be
even more.

Another idea is to advise the function responsible for inserting the abbrev to
the file: [[file:/home/luis/Documents/MyBlog/org/documentation/29.4-helpful-callable--insert-abbrev-table-description.html][insert-abbrev-table-description]].

#+begin_src emacs-lisp
(defun insert-abbrev-table-description (name &optional readable)
  "Insert before point a full description of abbrev table named NAME.
NAME is a symbol whose value is an abbrev table.
If optional 2nd arg READABLE is non-nil, insert a human-readable
description.

If READABLE is nil, insert an expression.  The expression is
a call to `define-abbrev-table' that, when evaluated, will define
the abbrev table NAME exactly as it is currently defined.
Abbrevs marked as \"system abbrevs\" are ignored."
  (let ((symbols (abbrev--table-symbols name readable)))
    (setq symbols (sort symbols 'string-lessp))
    (let ((standard-output (current-buffer)))
      (if readable
          (progn
            (insert "(")
            (prin1 name)
            (insert ")\n\n")
            (mapc 'abbrev--describe symbols)
            (insert "\n\n"))
        (insert "(define-abbrev-table '")
        (prin1 name)
        (if (null symbols)
            (insert " '())\n\n")
          (insert "\n  '(\n")
          (mapc 'abbrev--write symbols)
          (insert "   ))\n\n")))
      nil)))
#+end_src

#+begin_src emacs-lisp
(defun write-abbrev-file (&optional file verbose)
  "Write all user-level abbrev definitions to a file of Lisp code.
This does not include system abbrevs; it includes only the abbrev tables
listed in `abbrev-table-name-list'.
The file written can be loaded in another session to define the same abbrevs.
The argument FILE is the file name to write.  If omitted or nil, it defaults
to the value of `abbrev-file-name'.
If VERBOSE is non-nil, display a message indicating the file where the
abbrevs have been saved."
  (interactive
   (list
    (read-file-name "Write abbrev file: "
		            (file-name-directory (expand-file-name abbrev-file-name))
		            abbrev-file-name)))
  (or (and file (> (length file) 0))
      (setq file abbrev-file-name))
  (let ((coding-system-for-write 'utf-8))
    (with-temp-buffer
      (dolist (table
	           ;; We sort the table in order to ease the automatic
	           ;; merging of different versions of the user's abbrevs
	           ;; file.  This is useful, for example, when the
	           ;; user keeps their home directory in a revision
	           ;; control system, and therefore keeps multiple
	           ;; slightly-differing loosely synchronized copies.
	           (sort (copy-sequence abbrev-table-name-list)
		             (lambda (s1 s2)
		               (string< (symbol-name s1)
				                (symbol-name s2)))))
	    (if (abbrev--table-symbols table)
            (insert-abbrev-table-description table nil)))
      (when (unencodable-char-position (point-min) (point-max) 'utf-8)
	    (setq coding-system-for-write 'utf-8-emacs))
      (goto-char (point-min))
      (insert (format ";;-*-coding: %s;-*-\n" coding-system-for-write))
      (write-region nil nil file nil (and (not verbose) 0)))))
#+end_src

The way Emacs handles abbrevs may be better.  When I tried my function it was
very slow mostly because of the aligning.  I am wondering if.
