#+TITLE: company completion
#+AUTHOR: Luis Henriquez-Perez

I had used company previously many years ago.  At some point I stopped and for a
long time since I have not used any completion system.  Now I am at a point
where I am working out what tools I should use for text completin and how that
text completin should look like.  I wanted to see whether company is a good option
for me.  To achive this the first thing I did is to try to learn about company
via a minimal example.  I just wanted to get basic [[][dabbrev]] completion from
this blog post.

See [[https://www.monolune.com/articles/configuring-company-mode-in-emacs/][]]

By default =company= has a ton of backends.  I removed all backends in
=company-backends= except =company-capf=.  Considering how popular it has become to
use built-in Emacs intended extension features, I wanted to specifically test
company's ability to.

The first thing you see when checking the company backends is a long list of who
knows what.  For sure you do not need all this stuff at least in the org buffer
I am using.

#+begin_src emacs-lisp
(opt! company-minimum-prefix-length 1)

(setq-local company-backends '(company-capf))

(opt! dabbrev-check-all-buffers nil)
(opt! dabbrev-check-other-buffers nil)
(opt! cape-dabbrev-check-other-buffers nil)
#+end_src

# * company unexpected behavior when typing

# #+begin_src emacs-lisp
# (setq package-pinned-packages '((company . "melpa-stable") (org . "melpa-stable")))
# #+end_src

I encountered some kind of small unpredicatable behavior.  For example, when
beginning to type =v= I would get the proper suggestions: "Vivamus", "Volutpat",
"velit" and "vitae" but then if I choose to type "e" for the intention of
getting "velit" the popup would go away.  Instead I expected the the inline
preview to show (insce the choices should narrow down to one) until I finished
typing "velit".  For some reason company popup quits even when typing the same
characters as one of the candidates.

In contrast, corfu acts much more predictably.  Essentially, it did exactly what
I expected it to do all the time.

* adding text

I added this latin text from [[https://github.com/jschaf/emacs-lorem-ipsum][lorem-ipsum]] so I would have words in the buffer I
could try to match with =dabbrev=.

Aliquam erat volutpat.  Nunc eleifend leo vitae magna.  In id erat non orci
commodo lobortis.  Proin neque massa, cursus ut, gravida ut, lobortis eget,
lacus.  Sed diam.  Praesent fermentum tempor tellus.  Nullam tempus.  Mauris ac
felis vel velit tristique imperdiet.  Donec at pede.  Etiam vel neque nec dui
dignissim bibendum.  Vivamus id enim.  Phasellus neque orci, porta a, aliquet
quis, semper a, massa.  Phasellus purus.  Pellentesque tristique imperdiet
tortor.  Nam euismod tellus id erat.  Vivamus imperdiet.  Praesent
tristique. gravida lobortis fermentum.

* ensure to check only current buffer

I have noticed it is very easy to make company slow, much easier than corfu.
Just playing around with it and using essentially out of the box I ran into
noticeable delays in emacs-lisp buffers.  I have been trying to see if I can get
predictable resuts from both corfu and company.  I am surprised that cape has a
separate setting for checking other buffers.

With these settings I got essentially.  I got both company and corfu to
behave predictably in the current buffer.  volutpat

#+begin_src emacs-lisp
#+end_src

* isolate a backend

#+begin_src emacs-lisp
(add-hook 'completion-at-point-functions #'cape-dabbrev nil 'local)
(remove-hook 'completion-at-point-functions #'pcomplete-completions-at-point 'local)
#+end_src

* escaping with evil

I have this function bound to escape.  I have to rethink the function.  I think
it can be better done with a hook, specifically one that is run by
[[file:/home/luis/Documents/MyBlog/org/documentation/29.4-helpful-callable--run-hook-with-args-until-success.html][run-hook-with-args-until-success]].  Vivamus pellentesque Vivamus Pellentesque
pell.

#+begin_src emacs-lisp
(defun oo-dwim-escape ()
  "Exits out of whatever is happening after escape."
  (interactive)
  (when (bound-and-true-p evil-mode)
    (evil-normal-state 1))
  (cond ((minibuffer-window-active-p (minibuffer-window))
		 (if (or defining-kbd-macro executing-kbd-macro)
			 (minibuffer-keyboard-quit)
           (abort-recursive-edit)))
		((or defining-kbd-macro executing-kbd-macro) nil)
        (t
         (when (and (not buffer-read-only)
                    (buffer-file-name)
                    (buffer-modified-p))
           (save-buffer))
		 (keyboard-quit))))
#+end_src

* I was thnking I was getting bugs because of 

I do not know if it is just me but isolate but I tell you I was getting tons of
bugs from company.  I could not get it to do this simple thing.  When I
restarted my configuration and tried company again and changed the settings to
the following it worked well.  I am thinking of whether to use company as a
helper.  Though I would like a function that excludes
