#+title:sanitize file name
#+author:Luis Henriquez-Perez

While working on a [[file:2025-03-05T23.55.26_link_to_any_buffer.org][previous post]] I had the need to produce a proper file name
from a buffer name.  I remember I have needed to do it before and I wrote a
function for it but I do not think I saved the function.

I asked chatGPT and it recommend this function.

#+begin_src emacs-lisp
(defun oo-sanitize-filename (filename)
  "Replace bad characters in FILENAME with underscores."
  (let ((bad-chars "[ \t\n*/?\\[\\]()<>|&;!\"'`$=:%,@]"))
    (replace-regexp-in-string bad-chars "_" filename)))
#+end_src

I think the regexp is wrong because it keeps the brackets when I test it below.
I am glad that this result does not work because it acts as a good example.
The lesson is to always test stuff that is recommended by chatGPT or any A.I.

#+begin_src emacs-lisp
(buffer-name)
;; => "*Org Src 2025-03-06T09.18.40_sanitize_file_name.org[ emacs-lisp ]*"
(oo-sanitize-filename (buffer-name))
;; => "*Org Src 2025-03-06T09.18.40_sanitize_file_name.org[ emacs-lisp ]*"
#+end_src

Looking at the function chatGPT wrote, I think it is easier to just specify this
in the positive rather than the negative; to say letters, numbers, and a few
certain symbols are legal instead of specifying every illegal character.

Here is the regular expression.

#+begin_src emacs-lisp
(rx (not (any "-" "_" "." alnum)))
#+end_src

#+begin_src emacs-lisp
(defun oo-sanitize-filename (filename)
  "Replace bad characters in FILENAME with underscores."
  (replace-regexp-in-string "[^._[:alnum:]-]" "_" filename))
#+end_src

O.K., the results look better.  This function comes up.

#+begin_src emacs-lisp
(buffer-name)
;; => "*Org Src 2025-03-06T09.18.40_sanitize_file_name.org[ emacs-lisp ]*"
(oo-sanitize-filename (buffer-name))
;; => "_Org_Src_2025-03-06T09_18_40_sanitize_file_name_org__emacs-lisp___"
#+end_src
