#+TITLE: skempo: is it worth it?
#+AUTHOR: Luis Henriquez-Perez

I have been curious about this interesting package called [[https://github.com/xFA25E/skempo][skempo]].  It is an
attempt to unify the syntaxes of =tempo= and =skeleton= two template generators in
Emacs.  This is a laudable goal.  It is definitely a bit confusing deciding which templating system to use considering both are provided in Emacs.  Having just one system which takes the best of both would be ideal.

It is not available on melpa so I needed to install it via =package-vc=.  If you do it this way make sure to delete it afterwards if you do not want it permanently.

#+begin_src emacs-lisp
(package-vc-install '(skempo :url "https://github.com/xFA25E/skempo" :branch "master"))
#+end_src

Then formally load it.

#+begin_src emacs-lisp
(require 'skempo)
#+end_src

When I look at these variables all of them.

#+begin_src emacs-lisp
(opt! skempo-completing-read t)
(opt! skempo-delete-duplicate-marks t)
(opt! skempo-skeleton-marks-support t)
#+end_src

I do not know about this tag thing.  And I am not so font of having.  Also the docstring is kind of awkward pass in, whyd you want to pass it in.

#+begin_src emacs-lisp
(skempo-define-tempo let (:tag t)
  "(let ((" p "))" n> r> ")")
#+end_src

Is this package worth it?  Does it provide something that justifies the additional code and complexity it introduces?

To me the answer is no to both questions.  First, I do not plan to use the
tempel tag system.  This package seems mostly like a wrapper around defining
skeletons and tempo snippets.  Mainly it provides a convenient syntax to define
both of them and integration with abbrevs.  But other than that it does not
provide much more to me.
