#+title: Stop abbrev from expanding on newline
#+author: Luis Henriquez-Perez

For a long time I wanted to fix a particular behavior with abbrev expansion.
Namely, that by default =abbrev= will skip newlines when looking for a word to
expand.  This can causes me unexpected and more often than not undesired abbrev
expansions.  In this post I will document how I go about fixing this.

The first function that comes to mind to search for the problem is
unsurprisingly [[/home/luis/Documents/MyBlog/org/documentation/29.4-helpful--expand-abbrev.html][expand-abbrev]] then at [[/home/luis/Documents/MyBlog/org/documentation/29.4-helpful--abbrev-expand-function.html][abbrev-expand-function]] until finally I
found the culprit, [[/home/luis/Documents/MyBlog/org/documentation/29.4-helpful--abbrev--before-point.html][abbrev--before-point]].  The body of =abbrev--before-point= is
long and intimidating but the only part that concerns the problem is the
following chunk.  By default it uses [[/home/luis/Documents/MyBlog/org/documentation/29.4-helpful--backward-word.html][backward-word]] to find the previous
expansion.  And therein lies the problem.  The function =backward-word= finds the
last word regardless of how many lines it is behind point.  It has no
boundaries.  Notably, however, using any regexp will automatically bound the
search to the beginning of the current line as we can see to the call to
[[/home/luis/Documents/MyBlog/org/documentation/29.4-helpful--looking-back.html][looking-back]]: ~(looking-back re (line-beginning-position))~.  I do not know if
this was intentional.  If you bound =looking-back= why not bound =backward-word=?

#+begin_src emacs-lisp
(let ((re (abbrev-table-get table :regexp)))
  (if (null re)
      ;; We used to default `re' to "\\<\\(\\w+\\)\\W*"
      ;; but when words-include-escapes is set, that
      ;; is not right and fixing it is boring.
      (let ((lim (point)))
        (backward-word 1)
        (setq start (point))
        (forward-word 1)
        (setq end (min (point) lim)))
    (when (looking-back re (line-beginning-position))
      (setq start (match-beginning 1))
      (setq end   (match-end 1)))))
#+end_src

In any case, this suggests that what I need to do is provide a regexp and it
will automatically be bounded.  Conveniently the comment in the code provides a
good regexp to go by.  Sure it mentions [[/home/luis/Documents/MyBlog/org/documentation/29.4-helpful--words-include-escapes.html][words-include-escapes]] but to be
honest I do not really care about that.  I have got to say I am not sure if I
care about including escape sequences in words.  Yeah for this I am following
the principle I made up of: deal with problems only as they arise.  As of yet I
have not even dreamed of a need to include escape sequences in words.

#+begin_src emacs-lisp
(abbrev-table-put global-abbrev-table :regexp "\\<\\(\\sw+\\)\\Sw*")
#+end_src

