#+TITLE: potential change to config organization
#+AUTHOR: Luis Henriquez-Perez

When I was working on my configuration I noticed that there are functions from
 some packages that I want to have loaded preemptively.  For example, a cross
 configuring that often happens with evil is adding a function that enables
 insert state to certain mode hooks such as [[file:/home/luis/Documents/MyBlog/org/documentation/29.4-helpful-variable--git-commit-mode-hook.html][git-commit-mode-hook]].  Even if I
 define a function in my init file it is not guaranteed to be defined before
 certain other init files.  Right now, I just try to keep the cross configuring
 all in the [[../documentation/29.4-130-init-evil.html][130-init-evil.el]] and [[../documentation/29.4-990-config-evil.html][990-config-evil.el]] files.  I do not know.  It
 is something to think about.  I will try to do this as much as possible because
 I do not want to add another kind of file but I may have to have something like
 =evil-common.el= or maybe just one large =common.el= or even =cross-configure.el=
 with functions and macros that can be loaded immediately and are for cross
 configuration purposes.  These "common" files would all be run first, then the
 init-files and then the config files.
