#+TITLE: Objectives of Blog
#+AUTHOR: Luis Henriquez-Perez

This is a record of the thoughs and visions I had when writing this blog post.
This includes why I wrote it and what I aspire it to be as well as planned
discussion topics.  With this I strive to be clear, upfront and grounded.

* I want this blog to be...
- *informative*
  Every post should be information rich.
- *thorough*
  I should thoroughly explore topics.  I do not want this superficial stuff.
- *extensively documented*
  Everything that I am referecing should have a link to what I am referring to.
  In general each post will be link heavy.
- *thoughtful*
  The thoughts and descriptions I add should be high-quality.  It should be
  clear from reading as well as my references that the thoughts are
  well-informed.
- *honest and soulful* Part of the reason I wrote the blog as to use as a resume
  for employers to actually see my work.  But I am not trying to impress them.
  I want this blog to be unapologetic and frank.
- *visually appealing but minimal*
  Right now I have the minimal part down but am severly lacking in the "visually
  applealing" department because if my lack of experience with css.  But I will
  get there.  And I will be documenting exactly how I get there in this blog.
- *authentic* My site is *not* AI generated nor are the contents of my blog posts.
  It is written and planned be me, a human being.  At most I might use AI to
  research possible answer for a problem /and then confirm whether the answer is
  true or false/ before I use it because I have encountered /several/ cases where
  answers generated by AI have been wrong.
* I am writing this blog to...
- *document problems*
  Although there is a plethora of support in terms of stackoverflow questions
  blogs and articles about text and even the archwiki.  Often I found problems
  difficult to explain.
- *help others*
  I want others not to have to struggle as I have had with the problems I have
  encountered.  I have often had the experience where I have scowered the web
  for trying to figure out a difficult problem.
- *help myself*
  I have moments when I forget exactly what I did or how I did it and in those
  moments I would like an account of how I did something.
- *document how to teach yourself*
  I want to show the process of how I think about problems and how I go about
  devising solutions to them and learning about them.  And how I go about
  figuring them out without a teacher or mentor or boss telling me what to do.
- *be a resume*
  I want this to serve a repository for my work.  In my past I have been
  notoriously bad at saving my work and reusing it and really advertising
  myself.
* I am writing about...
- Manifestation of various things
- Emacs adventures
- Archlinux gotchas
- Cooking from nothing
- Math from nothing
- Improving willpower
- Buddhist Philosophy
- And more...
