#+title: gracefully loading init files
#+author: Luis Henriquez-Perez

It is time I refactor how I load my init files.

Also see [[https://emacs.stackexchange.com/questions/669/how-to-gracefully-handle-errors-in-init-file][]]

The idea of mine was inspired by multiple packages I have seen online--init
loaders: [[][Pinit-loader]] [[][Pel-init-loader]].  These are packages that load
parts of your emacs configuration for you but with the added benefit of doing
things like profiling your startup time or handling errors.

The former package requires you to name your files by loading order.  Whereas
=el-init-load= circimvents this by advising require and checking whether any of
the packages you load are.  Both packages do have a drawback: if compiling your
emacs configuration is a goal as it is for me the compiler does not know your
requiring these features since the function.

There is more to this though.  Thus far I have been maintaining a list of files
I require in my init file.  This is not the best design.  I have had problems.
Whenever I remove one of these files and forget to remove the corresponding line
I get an error.  Also I need to make sure these lines are in the right order
because order does matter--at least for some elements.  I no longer want to have
to actively maintain this and I also do not want to manage the order.  With this
in mind, my idea is to name files by number and keep.  Admittedly it is not as
pretty as just having names.

#+begin_src emacs-lisp
(require 'init-no-littering)
;; Built-in packages
(require 'init-abbrev)
(require 'init-auto-insert)
(require 'init-custom)
(require 'init-dired)
(require 'init-emacs-lock)
(require 'init-minibuffer)
(require 'init-saveplace)
(require 'init-vc-hooks)
(require 'init-window)
;; External packages
(require 'init-ace-window)
(require 'init-aggressive-indent)
(require 'init-avy)
(require 'init-buffer-terminator)
(require 'init-burly)
(require 'init-captain)
(require 'init-consult)
(require 'init-corfu)
(require 'init-corfu-history)
(require 'init-corfu-quick)
(require 'init-dashboard)
(require 'init-dirvish)
(require 'init-easy-escape)
(require 'init-emmet)
(require 'init-emms)
(require 'init-eshell)
#+end_src

* helper
:PROPERTIES:
:ID:       20250120T225833.758608
:END:

I am going to be renaming a bunch of files here and I do want to ensure that I
do not have to do lots of editing as well.  Obviously I want to make this as
painless as possible.  I am surprised this does not exist but I could not find it.

#+begin_src emacs-lisp
;; I am a bit surprised this does not exist.
(defun! oo-rename-library (oldname newname)
  "Rename a library and replace all references.
OLDNAME is the current library name, and NEWNAME is the new name."
  (interactive (list (read-file-name "old name: ")
                     ;; There are many ways to do this but just settle for simplest for now.
                     (read-string "new name: ")))
  (set! newname (expand-file-name (concat newname ".el") (f-dirname oldname)))
  (message "oldname %S newname %S" oldname newname)
  (return!)
  (rename-file oldname newname)
  (set! regexp (regexp-quote oldname))
  (set! lisp-file-regexp ".+\\.el\\'")
  (set! files (append (directory-files (expand-file-name "lisp") t lisp-file-regexp)
                      (list user-init-file)
                      (directory-files (expand-file-name "test") t lisp-file-regexp)))
  ;; Replace the name of the symbol in file.
  (dolist (file files)
    (with-temp-file file
      (insert-file-contents file)
      (goto-char (point-min))
      (while (re-search-forward regexp nil t)
        (replace-match (f-base newname))))))
#+end_src

I always forget how to use =interactive= so I looked at [[/home/luis/Documents/MyBlog/org/documentation/29.4-helpful--rename-visited-file.html][rename-visited-file]] as an
example (I tried [[/home/luis/Documents/MyBlog/org/documentation/29.4-helpful--rename-file.html][rename-file]] but that is written in C).

I have got to be honest.  There are so many ways for prompting renaming the
library that I am not sure how it should be done.  I think it might be easier to
separate the non-interactive and interactive parts of this function.  Note this
function is not general, it is specifically designed for my emacs configuration.

* creating a dired variant
#+begin_src emacs-lisp
(defun dired-do-rename (&optional arg)
  "Rename current file or all marked (or next ARG) files.
When renaming just the current file, you specify the new name.
When renaming multiple or marked files, you specify a directory.
This command also renames any buffers that are visiting the files.
The default suggested for the target directory depends on the value
of `dired-dwim-target', which see.

Also see `dired-do-revert-buffer'."
  (interactive "P")
  (when (seq-find (lambda (file)
                    (member (file-name-nondirectory file) '("." "..")))
                  (dired-get-marked-files nil arg))
    (user-error "Can't rename \".\" or \"..\" files"))
  (dired-do-create-files 'move #'dired-rename-file
			             "Move" arg dired-keep-marker-rename "Rename"))
#+end_src

* what I did at first

That is what I did at first but I realized it would still be a pain to change
everything.  I have lots of files.

#+begin_src emacs-lisp
(defun oo--ensure-library-name (file)
  ;; Check to see if what it provides is different from the file name.
  ;; If it is use the filename.
  (with-temp-file file
    (insert-file-contents file)
    (goto-char (point-main))
    (re-search-forward "")
    ;; When the feature name is different from the filename
    (when ()
      ())))
#+end_src
