#+TITLE: using mono-complete
#+AUTHOR: Luis Henriquez-Perez

Even before Emacs 30 came out with a new built-in package, [[https://git.sr.ht/~eshel/completion-preview][completion-preview]], I
had wanted a package that suggested completions in a more minimal and less
unintrusive display than the staple popups menu from packages like [[https://github.com/minad/corfu][corfu]] and
[[http://company-mode.github.io/][company]].  I was looking which are distracting and lend themselves to being
deterimental to performance.  I have had a few fraught attempts moving to Emacs
30 so I thought why not try this package which is very similar.

#+begin_src emacs-lisp
(opt! dabbrev-check-all-buffers nil)
(opt! dabbrev-check-other-buffers nil)
#+end_src

By default in org I only have [[file:/home/luis/Documents/MyBlog/org/documentation/29.4-helpful-callable--pcomplete-completions-at-point.html][pcomplete-completions-at-point]].

#+begin_src emacs-lisp
(add-hook 'completion-at-point-functions #'cape-dabbrev nil 'local)
(remove-hook 'completion-at-point-functions #'pcomplete-completions-at-point 'local)
#+end_src

The first question I have is on the =capf= backend.  It says in the README that it
uses [[file:/home/luis/Documents/MyBlog/org/documentation/29.4-helpful-variable--completion-at-point-functions.html][completion-at-point-functions]].  So I expect that when I set
=completion-at-point-functions= to ~(cape-dabbrev t)~ that it will get the top
result from invoking ~(completion-at-point)~ at the current point.  But instead I
get weird completions.  Question current question curre

#+begin_src emacs-lisp
(opt! mono-complete-backends '(capf))
(opt! mono-complete-evil-insert-mode-only t)
(opt! mono-complete-cache-directory (expand-file-name "monocomplete" oo-var-dir))
#+end_src

Obvious I like the mono-complete is flexible.  My main problem with it is that
it departs a bit from hfl
