#+title: profiling startup time
#+author: Luis Henriquez-Perez

I have designed my emacs configuration with the purpose of minimizing my init
time.  I have done staple things like disabling garbage collection and file
handlers, I have set certain recommended variables such as
[[/home/luis/Documents/MyBlog/org/documentation/29.4-helpful--bidi-display-reordering.html][bidi-display-reordering]] and [[/home/luis/Documents/MyBlog/org/documentation/29.4-helpful--idle-update-delay.html][idle-update-delay]], and most importantly I lazy load
all unneeded packages.  Sadly, even with all this my startup is still at a
whopping =3.29= seconds.

The first step to reducing startup time is simply to find out what parts of your
configuration is responsible.  Here the [[https://en.wikipedia.org/wiki/Pareto_principle][80-20 principle applies]]: 20% of your
emacs configuration (or less) is responsible for 80% or more of the startup
time.  There are several packages that offer profiling for emacs like [[https://github.com/jschaf/esup][esup]] or
[[https://www.emacswiki.org/emacs/ProfileDotEmacs][ProfileDotEmacs]].  I do not have much experience with the latter but I have used
=esup= before and it is pretty good, when it works that is.  Lately when I use it
I run into problems with.  It should not be this hard.

# To be honest this is one of the biggest reasons why not to use emacs (not that
# this is a big reason, but of the reasons not to use emacs this is one of the
# biggest).  It is hard to get startup low even after trying very hard.  It is the
# opposite with vim, it is hard to get the startup very high unless you mess up.

The following macro is a wrapper around [[/home/luis/Documents/MyBlog/org/documentation/29.4-helpful--require.html][require]].  In addition to loading a
feature it logs the time it took for the feature to be loaded.  And if loading
the feature should result in an error, it suppresses the error and logs it.
What this means for my config is I will know preciesely how much time loading
each file will take.  Also, my configuration will not short circuit if I get an
error in an init file.

#+begin_src emacs-lisp
(defmacro require! (feature &optional path)
  "Catch any errors, record and log the time taken to require FEATURE."
  `(let ((start (current-time))
         (feature ',feature)
         (time nil))
     (condition-case err
         (progn
           (require ',feature ,path)
           (setq time (string-to-number (format "%.2f" (float-time (time-subtract (current-time) start)))))
           (oo-log 'info "Required '%s in %.2f seconds" feature time))
       (error
        (oo-log 'error "Error requiring '%s: %s" feature err)))
     (push (list feature time) oo-init-data)))
#+end_src

I have made a big decision with my file organization: I decided to prefix most
of my files with three digits.  And the order of the digits correspond to the
order in which the files should be loaded.  The downside is the file names look
ugly.  But the reason I did this is that it makes the logic for loading files
much easier.  This is good programmatically but it also makes things
transparent.

I use this macro in another macro, =load!=.
#+begin_src emacs-lisp
(defmacro load! (dir)
  (let (forms feature)
    (setq dir (expand-file-name dir user-emacs-directory))
    (dolist (path (directory-files dir t "^[[:digit:]][[:digit:]][[:digit:]].+\\.el$"))
      (setq feature (intern (file-name-sans-extension (file-name-nondirectory (directory-file-name path)))))
      ;; It is a bit faster if you specify the path because then emacs does not have to look through the directory.
      (push `(require! ,feature ,path) forms))
    `(progn ,@(nreverse forms))))
#+end_src

[[../documentation/log-buffer.html][foo]]

With these two macros I.
