#+title: inserting org links painlessly with abbrevs
#+author:Luis Henriquez-Perez

It is such a pain to type links out manually.  Fortunately, abbrevs
can inserting links quick and painless by using abbrevs.

* function for determining if I am writing a blog post

I use abbrevs a bit differently than what is suggested in the [[][manual]].  In
the manual it is recommneded to use multiple abbrev table, one for each mode
you want abbrevs for and if you ever one more than one abbrev table active you
can modify the local abbrev table variable.  Instead I just use one table, the
global abbrev table, distinguish where each links should go via the abbrev's
[[][:enable-function]] property.  The enable property needs to return non-nil when the abbrev is active.

#+begin_src emacs-lisp
(defun oo-blog-post-p ()
  "Return non-nil if the current buffer is for one of my blog posts."
  (declare (pure t) (side-effect-free error-free))
  (and (derived-mode-p 'org-mode)
       (stringp default-directory)
       (string= (expand-file-name default-directory)
                (expand-file-name "~/Documents/MyBlog/org/posts/"))))
#+end_src

* blog link to function documentation

Perhaps the most common links I use in my blog are those to callable and variable documentation.  The idea here is to write an abbrev that upon expansion will prompt me for a callable to document and when I select that callable it will link it to the corresponding documentation in my blog's "documentation" folder.  If the documentation for said callable does not exist, then it will look up the documentation via [[https://github.com/Wilfred/helpful][helpful]] and save it to the documentation folder beforehand.  Pretty cool huh?  This is about as efficient as we can get inserting such a link.

#+begin_src emacs-lisp
(defun! oo-expand-function-doc-link ()
  "Expand an org link for a configuration file."
  (set! doc-dir (expand-file-name "~/Documents/MyBlog/org/documentation/"))
  (set! helpful-switch-buffer-function #'ignore)
  (set! symbol (helpful--read-symbol "Callable: " (helpful--callable-at-point) #'fboundp))
  (setq html-file (expand-file-name (format "%s-helpful--%s.html" emacs-version symbol) doc-dir))
  (unless (file-exists-p html-file)
    (and (setq help-buffer (helpful-callable symbol))
         (setq html-buffer (htmlize-buffer help-buffer))
         (progn (with-current-buffer html-buffer
                  (write-region (point-min) (point-max) html-file nil 'quiet))
                (kill-buffer help-buffer)
                (kill-buffer html-buffer))))
  (insert (format "[[file:%s][%s]]"  html-file symbol)))

(define-abbrev global-abbrev-table "flk" "" #'oo-expand-function-doc-link
  :enable-function #'oo--in-org-p)
#+end_src

* blog link to variable documentation

Obviously we want this for variables too.  And the process is essentially the same except we use the helpful functions correspond to variables instead.

#+begin_src emacs-lisp
(defun! oo-expand-var-documentation ()
  "Expand an org link for a configuration file."
  (setq doc-dir (expand-file-name "../documentation"))
  (set! lisp-dir (expand-file-name "lisp" user-emacs-directory))
  (appending! files (directory-files lisp-dir t (rx ".el" eol)))
  (pushing! files (expand-file-name user-init-file))
  (pushing! files (expand-file-name "early-init.el" user-emacs-directory))
  (set! path (completing-read "" files))
  (insert (format "[[%s][%s]]"  path (file-name-nondirectory path))))
#+end_src

* package link documentation

Often when writing blog posts I have wanted to link to Emacs packages I talk
about.  The idea is to write an abbrev that prompt me for a package and once I select one it will insert an org link to the package.  Writing this I did not know how to do select a package via [[file:/home/luis/Documents/MyBlog/org/documentation/29.4-helpful-callable--completing-read.html][completing-read]], or rather how to list the set of packages to choose from via =completing-read= but I found out by looking at the definition for [[file:/home/luis/Documents/MyBlog/org/documentation/29.4-helpful-callable--package-install.html][package-install]].

#+begin_src emacs-lisp
(mapcan
 (lambda (elt)
   (and (or (and (or current-prefix-arg
                     package-install-upgrade-built-in)
                 (package--active-built-in-p (car elt)))
            (not (package-installed-p (car elt))))
        (list (symbol-name (car elt)))))
 package-archive-contents)
#+end_src

I also did not know how to get the link that corresponds to a package off the
top of my head.  So I looked in [[file:/home/luis/Documents/MyBlog/org/documentation/29.4-helpful--package-browse-url.html][package-browse-url]] to see how that was done.

#+begin_src emacs-lisp
(cdr (assoc :url (package-desc-extras desc)))
#+end_src

One thing to always keep in mind when dealing with packages is that they are handled represented via package description objects.  I realized the aforementioned code used by =package-install= would give me a list of package symbols but what I actually needed was a way to get a description object which, fortunately, is what [[file:/home/luis/Documents/MyBlog/org/documentation/29.4-helpful-callable--package--query-desc.html][package--query-desc]] provides. 

#+begin_src emacs-lisp
(defun! oo-expand-package-link ()
  "Prompt for package and insert the corresponding org package link."
  (set! desc (package--query-desc))
  (set! link (cdr (assoc :url (and desc (package-desc-extras desc)))))
  (insert (format "[[%s][%s]]" link (package-desc-name desc))))

(define-abbrev global-abbrev-table "plk" "" #'oo-expand-package-link
  :enable-function #'oo-blog-post-p)
(define-abbrev global-abbrev-table "plink" "" #'oo-expand-package-link
  :enable-function #'oo-blog-post-p)
#+end_src

* a version of getting the package link

This let's me produce the package link.

#+begin_src emacs-lisp
(defun oo-expand-package-link ()
  "Expand package-link."
  (set! desc (package--query-desc))
  (set! link (cdr (assoc :url (and desc (package-desc-extras desc)))))
  (insert (format "[[%s][%s]]" link (package-desc-name desc))))
#+end_src

* link to configuration files

Although the most often links I have are to callables or functions, occasionally I will want to link to one of my configuration files.

#+begin_src emacs-lisp
(defun! oo-expand-config-link ()
  "Expand an org link for a configuration file."
  (setq doc-dir (expand-file-name "~/Documents/MyBlog/org/documentation/"))
  (set! lisp-dir (expand-file-name "lisp" user-emacs-directory))
  (appending! files (directory-files lisp-dir t (rx ".el" eol)))
  (pushing! files (expand-file-name user-init-file))
  (pushing! files (expand-file-name "early-init.el" user-emacs-directory))
  ;; Save a snapshot of my configuration file.
  (set! config-file (completing-read "" files))
  (set! html-file (expand-file-name (file-name-nondirectory file) doc-dir))
  (set! config-buffer (create-file-buffer config-file))
  (set! html-buffer (htmlize-buffer config-buffer))
  (unless (file-exists-p html-file)
    (with-current-buffer html-buffer
      (write-region (point-min) (point-max) html-file nil 'quiet)))
  (kill-buffer html-buffer)
  ;; TODO: make the file path relative.
  (insert (format "[[file:%s][%s]]" html-file (file-name-nondirectory path))))

(define-abbrev global-abbrev-table "clk" "" #'oo-expand-config-link :enable-function #'oo-blog-post-p)
(define-abbrev global-abbrev-table "clink" "" #'oo-expand-config-link :enable-function #'oo-blog-post-p)
#+end_src

* generally add a buffer to the documentation

Although the links I wrote are undoubtedly useful there are times when I want to link to a buffer that is nether helpful documentation nor a config file.  In that case I want a generic function that will take a buffer and.

#+begin_src emacs-lisp
(defun oo-add-to-blog-docs ()
  "Take an html snapshot of the current buffer and add it to blog."
  (interactive)
  (set! doc-dir (expand-file-name "~/Documents/MyBlog/org/documentation/"))
  ;; Add a timestamp to the thing.
  (set! html-buffer (htmlize-buffer (current-buffer)))
  (read-string "Name: " (buffer-name))
  (set! html-file (expand-file-name (format "$s")))
  (with-current-buffer html-buffer
    (write-region (point-min) (point-max) html-file nil 'quiet))
  (kill-buffer html-buffer))
#+end_src

* reference blog documentation

Naturally, after adding I will want to.
 
#+begin_src emacs-lisp
(defun oo-reference-blog-doc ()
  "Take an html snapshot of the current buffer and add it to blog."
  (interactive)
  (set! doc-dir (expand-file-name "~/Documents/MyBlog/org/documentation/"))
  ;; Remove timestamp from the name.
  ;; Get name of thing based on buffer name.
  ;; Add a timestamp to the thing.
  (insert (format "[[file:%s][%s]]" file (file-name-non-directory name))))
#+end_src

* blog link to another one of my posts

#+begin_src emacs-lisp
;; Prompt me for a config file.
(defun! oo-block-post ()
.  ""
  (set! blog-dir ())
  
  )
#+end_src
