#+title: protocol for adding hooks
#+author: Luis Henriquez-Perez

I have struggled a bit with hooks, perhaps a symptom of over-engineering.  Right
now instead I will.  Essentially, I have wanted to add certain properties to
hooks.  I will document the cases I wish to handle well.

* case 1: adding a named function to a hook

In this case I do not want to add the original function to the hook because I
want the function to do "special" hook things.  Namely, suppress errors and log
it is usage.

* case 2: creating a new hook

Sometimes I need to create a new hook altogether that is not based on an
existing name.  For example, in emacs there are cases when you need to set a
local variable during a mode.  And in that case there's no function per se.

* decision

Based on these cases I think it would be best to have a function that generates
a hook.  The function should generate a hook function given the function that
should be called as the body.  The function could be a symbol function or an
anonymous lambda.

* naming convention

Since I am creating specific functions for hooks.
