#+title:draft preventing lag for package install
#+author:Luis Henriquez-Perez

In a [[file:draft_][previous post]] I wrote about profiling the function [[/home/luis/Documents/MyBlog/org/documentation/29.4-helpful--package-initialize.html][package-initialize]]
I discovered that the function [[/home/luis/Documents/MyBlog/org/documentation/29.4-helpful--package-read-all-archive-contents.html][package-read-all-archive-contents]] and I removed
it.  Although it was not necessary for startup, there was a reason why it was
there.  Without it, when I invoke [[/home/luis/Documents/MyBlog/org/documentation/29.4-helpful--package-install.html][package-install]] for the first time I see a
message that.

[[][]]

I noticed that if I invoked =package-read-all-archive-contents= before calling
package install (via [[/home/luis/Documents/MyBlog/org/documentation/29.4-helpful--eval-expression.html][eval-expression]]) then =package-install= would
work as expected.  Well, fortunately.

#+begin_src emacs-lisp
(defun oo--read-archive-contents (&rest _)
  (package-read-all-archive-contents)
  (advice-remove 'package-install #'oo--read-archive-contents))

(advice-add 'package-install :around #'oo--read-archive-contents)
#+end_src

That did not work.  I think that taught me one of the limitations of advice.  I
do not think advice works for interactive forms.  The advice I used did not work
as expected.  At first I thought that it was a mistake in my before advice, but
then I realized that both my before and after advices wrent working.  Then I
looked at the body of the and saw that the comments were happening why
[[/home/luis/Documents/MyBlog/org/documentation/29.4-helpful--package--archives-initialize.html][package--archives-initialize]].

#+begin_src emacs-lisp
(defun oo--read-archive-contents (orig-fn &rest args)
  (prog2 (package-read-all-archive-contents)
      (apply orig-fn args)
    (advice-remove 'package-install #'oo--read-archive-contents)))

(advice-add 'package--archives-initialize :around #'oo--read-archive-contents)
#+end_src

When I used this advice it worked perfectly.  Now package-install prompt happens
instantly.
