#+TITLE: installing completion preview for Emacs 29.4
#+AUTHOR: Luis Henriquez-Perez

Twice now I have migrated to Emacs 30 only to have to revert back to Emacs 29.4
because of various annoying little problems.  The biggest motivating factor for
me was the cool new built-in package =completion-preview=.  In hindsight I realize
this is not even close to a good enough reason for switching but.  Now I realize
I can simply install that package.  Just for stability reasons.  I mean the new
Emacs release was just a few days ago, so its fresh and not as rigoriously
tested as the forurth release of version 29.

First I am attempting to install the package.  Ihn done this before.  Looking
online the link for installing completion-preview is.  But when I try to install
it I get.

#+begin_src emacs-lisp
(package-vc-install '(completion-preview :url "https://github.com/emacs-mirror/emacs/blob/master/lisp/completion-preview.el"))
#+end_src

#+begin_src emacs-lisp
(package-vc-install '(completion-preview :main-file "https://github.com/emacs-mirror/emacs/blob/master/lisp/completion-preview.el"))
#+end_src

#+begin_src emacs-lisp
(package-vc-install '(completion-preview :url "https://github.com/emacs-mirror/emacs/blob/master/lisp/completion-preview.el"))
#+end_src

My mistake was using the link from Emacs mirror.  And this stemmed from a
mistkae in how I searched for the package.  I googled "completion-preview-mode"
instead of "completion-preview".  When I googled.  With the correct link simply
add it to =package-selected-packages= and called
[[file:/home/luis/Documents/MyBlog/org/documentation/29.4-helpful-callable--package-vc-install-selected-packages.html][package-vc-install-selected-packages]].

#+begin_src emacs-lisp
(setq package-vc-selected-packages '((completion-preview :url "https://git.sr.ht/~eshel/completion-preview")
                                     (emacs-wallpaper :url "https://github.com/Luis-Henriquez-Perez/emacs-wallpaper" :branch "mine")
                                     (escr :url "https://github.com/Luis-Henriquez-Perez/escr")
                                     (evil-easymotion :url "https://github.com/Luis-Henriquez-Perez/evil-easymotion" :branch "master")
                                     (on :url "https://github.com/ajgrf/on.el")
                                     (outli :url "https://github.com/jdtsmith/outli")
                                     (zone-matrix :url "https://github.com/ober/zone-matrix" :branch "master")))
#+end_src

Of course it is possible to install it directly with [[file:/home/luis/Documents/MyBlog/org/documentation/29.4-helpful-callable--package-vc-install.html][package-vc-install]].

#+begin_src emacs-lisp
(package-vc-install '(completion-preview :url "https://git.sr.ht/~eshel/completion-preview"))
#+end_src

On Emacs 30 I found that a function =ispell-completion-at-point= in
=completion-at-point-functions=.

#+begin_src emacs-lisp
(opt! completion-preview-minimum-symbol-length 1)
(opt! completion-preview-idle-delay 0.2)

(remove-hook 'completion-at-point-functions #'ispell-completion-at-point t)
#+end_src
 
