#+title: Reviving the Blog
#+author: Luis Henriquez-Perez

* learning from my hiatus

It has to be at over a year since I have written my last blog post.  It is hard
for me to pinpoint when exactly I stopped but I do know that at some point
writing blog posts stopped being enjoyable for me.  It was not because I found
recounting what I did tedious or anything.  Actually, I enjoyed that.  Rather it
is was how difficult and cumbersome it had become to write a blog post.  After
much deliberation I had chosen to write the blog in pure html and css.  And at
the time it seemed like the right decision.  I wanted to to keep things simple
and I saw using org as adding an unnecessary layer of complexity between me and
the source code.  In hindsight I see that I underestimated how unpleasant it
would be to write blog posts in html.

The major problem is the prevalence of boilerplate.  HTML tags consume lots of
space and compel me to place the blog contents in indented, nested paragraph
tags.  To make matters worse, Emacs does not have the same link hidding features
that it does for org--or at least I could not find them.  This means that each
link in a paragraph results long, visually distracting and difficult to read
line.  In combination with my link-heavy writing this makes paragraphs I write
virtually unreadable.

Moreover, I was missing out on org's ability to automatically syntax highlight
source blocks; having to instead do it myself [[http://xahlee.info/emacs/emacs/elisp_htmlize.html][similar to Xah Lee]].

* what I am doing differently now

The idea is work smarter not harder.  I want to simply focus on the content of
my blog and how rapidly I can write a single blog post.  To that end, I will
structure my blog around [[https://orgmode.org/][Org]], a much lighter markup lnaguage with a plethora of
support in emacs.  For those that may be unfamiliar emacs provides a function
[[/home/luis/Documents/blog/org/documentation/29.4-helpful--org-publish.html][org-publish]] whereby you can write blog posts in Org.  If it is easy and
painless to write a blog post, then I will be able to maintain the daily habit.

# * what creates syntax highlighting for source blocks
# :PROPERTIES:
# :ID:       20250117T232221.903608
# :END:

# On its own the automatic syntax highlighting org provides in source blocks is
# enough reason to manage a blog with org.

# Despite having done it before I had some difficulty determining out how to get
# org to syntax highlight source blocks.  I peeked at the messages.  When I looked
# at time when running my org-publish script I was getting the message "".  The
# message is referring to [[https://github.com/hniksic/emacs-htmlize][htmlize]], an external emacs package.  I noticed
# when I used =htmlize= the proper tags were being added to the source code.
# However, it still was not properly colored.  When I looked at the faces it was
# using I realized none of them were faces I had defined.

# * css

# A major problem with my blog prior to now is how ugly it looked.  I barely
# styled it.

# * publishing

