#+title:first impressions after upgrading to emacs 30
#+author:Luis Henriquez-Perez

Just 5 minutes before writing this post I have upgraded to Emacs 30.  I had a
bit of a hiccup when =consult-buffer= raised an error instead of using the
completion prompt.  I figured it had to do with Emacs 30 coming with native
compilation by default and all my packages having been compiled with non-native
Emacs 29.  I simply rebuilt all my packages via [[file:/home/luis/Documents/MyBlog/org/documentation/30.1-helpful-callable--package-recompile-all.html][package-recompile-all]] and then I
had no problems.

* completion-preview-mode

What made me want to move over so quickly is the built-in completion suggestion
Emacs 30 offers.  I liked that it was less intrusive than a popup constantly
appearing near your cursor.  This non-intrusiveness was apparently something the
creator had in mind according to [[https://eshelyaron.com/posts/2023-11-17-completion-preview-in-emacs.html][this post]].  Coincidentally just recently I had
been looking into [[https://github.com/phillord/pabbrev][pabbrev]], a package that also has this kind of selection, as an alternative to [[https://github.com/minad/corfu][corfu]].

I wanted to get =completion-preview-mode= to work when writing in org-mode but for
some reason I could not get it to work.  I simply wanted the completion preview
to recommend words I had already typed in the buffer.  I added suggestions from
[[file:/home/luis/Documents/MyBlog/org/documentation/30.1-helpful-callable--cape-dabbrev.html][cape-dabbrev]] but it still do not suggest anything.  In contrast, the suggestions
did work in =emacs-lisp-mode=.  I do not know if its a
[[file:/home/luis/Documents/MyBlog/org/documentation/30.1-helpful-variable--completion-at-point-functions.html][completion-at-point-functions]] problem because invoking [[file:/home/luis/Documents/MyBlog/org/documentation/30.1-helpful-callable--completion-at-point.html][completion-at-point]] does
give me the =dabbrev= suggestions.

* Problems

** custom evil operator was bugged

Other issues came up when I was using Emacs 30.  One thing was that the evil
change inner functions I had defined stopped working, specifically the form
changing functions.  Rebuilding my packages did not work.  And then vertico
started giving me an error that the function =static-if= was void.  I think this
happened because I upgraded my version of vertico and that version was designed
for Emacs 30.  So I got vertico from melpa-stable but now the marginalia stuff
is not showing up on the side for certain commands such as.

Fuck, the static-if thing is now happening with helpful as well.  Good damn it.
The same thing happened with.  Again I fixed it by reinstalling [[https://github.com/Wilfred/helpful][helpful]] from
melpa-stable.  Yeah this is a pain though having to be careful with this and do
this all the time and experiencing a change of behavior.

So I downgraded to Emacs 29.4 and thus far the main problem I am encountering is
that marginalia info does not always work I do not know if this is because of me
getting a version of vertico from melpa stable or what.  I am going to be
honest, this made me reconsider my desicion to not use [[][elpaca]].  By version
controlling your packages you do not have to deal with this shit.  My main issue
with elpaca right now is.

#+begin_src emacs-lisp
(add-hook 'completion-at-point-functions #'cape-dabbrev nil t)
;; (remove-hook 'completion-at-point-functions #'ispell-completion-at-point t)
#+end_src

Finally I got what seems to be unnoticeably different setup from what I had before.  I reinstalled all my packages.
