#+title:looking into skeletons
#+author:Luis Henriquez-Perez

I saw [[https://blog.einval.eu/2025/02/emacs-skeletons-the-missing-manual/][this post]] really made me want to give skeletons a try.

Because of inconveniences using [[https://github.com/minad/tempel][tempel]] I have considered migrating to some other
templating system faltn.  Some of my woes stem from Tempel's overlays.
They annoyingly presist unless you properly finish traversing the template and
they require special functions to properly get rid of them such as [[file:/home/luis/Documents/MyBlog/org/documentation/29.4-helpful-callable--tempel-done.html][tempel-done]]
or [[file:/home/luis/Documents/MyBlog/org/documentation/29.4-helpful-callable--tempel-abort.html][tempel-abort]].  And for the life of me I have not been able to avoid the
insertion of an extra space after I insert a template via an abbrev.  I am aware
from [[http://xahlee.info/emacs/emacs/emacs_abbrev_no_space.html][Xah's post]] on abbrevs that I need to add the =no-self-insert= property to the
expansion function, but I tried this and it did not work tempel templates.

#+begin_src emacs-lisp
(defun oo-expand-elisp-defun ()
  "Insert elisp defun template."
  ;; This is the template from tempel-collection.
  (tempel-insert 'fn))

;; "Insert elisp defun template."
;; '("(defun " p " (" p ")" n> "\"" p "\"" n> r ")")

;; (define-abbrev global-abbrev-table "dfn" "" #'oo-expand-elisp-defun :enable-function #'oo-in-elisp-mode-p)
#+end_src

In contrast to tempel, skeleton uses no overlays.  You never have to think about
cleaning overlays up and deleting the template is done the same way you would
delete any other text.  And the =no-self-insert= property worked perfectly.

#+begin_src emacs-lisp
(define-skeleton oo-expand-elisp-defun
  "Expand to a `defun' form."
  nil
  "(defun " @ - " (" @ ")" \n
  > "\"" @ "\""
  > @ _ \n ")" @)
#+end_src

The main thing I miss from tempel is the ability to traverse different template
locations.  Skeleton puts the positions specified by =@= into the variable
[[file:/home/luis/Documents/MyBlog/org/documentation/29.4-helpful-variable--skeleton-positions.html][skeleton-positions]] but there is no function for traversing to each position akin
to [[file:/home/luis/Documents/MyBlog/org/documentation/29.4-helpful-callable--tempel-next.html][tempel-next]] and [[file:/home/luis/Documents/MyBlog/org/documentation/29.4-helpful-callable--tempel-previous.html][tempel-previous]].  Fortunately, there is some pretty good code
from this [[https://www.emacswiki.org/emacs/SkeletonMode][emacswiki article]] on doing this.

#+begin_src emacs-lisp
(defvar *skeleton-markers* nil
  "Markers for locations saved in skeleton-positions")

(oo-add-hook 'skeleton-end-hook 'oo-skeleton-make-markers)

(defun oo-skeleton-make-markers ()
  "Create and return a list of markers corresponding to `skeleton-positions'."
  (while *skeleton-markers*
    (set-marker (pop *skeleton-markers*) nil))
  (setq *skeleton-markers*
	    (mapcar 'copy-marker (reverse skeleton-positions))))

(defun oo-skeleton-next-position (&optional reverse)
  "Jump to next position in skeleton.
REVERSE - Jump to previous position in skeleton"
  (interactive "P")
  (let* ((positions (mapcar 'marker-position *skeleton-markers*))
	     (positions (if reverse (reverse positions) positions))
	     (comp (if reverse '> '<))
	     pos)
    (when positions
      (if (catch 'break
	        (while (setq pos (pop positions))
	          (when (funcall comp (point) pos)
		        (throw 'break t))))
	      (goto-char pos)
	    (goto-char (marker-position
		            (car *skeleton-markers*)))))))
#+end_src

I would also like some nice placeholders for each field.  Placeholders make it
much clearer what is expected in each field.  Moreover, they avoid indentation
glitches.  When you use this defun template you will notice that the indentation
for the docstring is way off at first and that is because the =defun= name is
missing and that messes up the rest of the indentation.  Emacs gets confused and
thinks the arguments are the defun name.  Using [[https://github.com/Malabarba/aggressive-indent-mode][aggressive-indent]] it gets fixed
once you type something for the =defun= name so it is no big deal, but it is
slightly jarring.  The placeholders would make the indentatoin right from the
beginning.  But I do admit I do not need them and can certainly live without
them.

I would like to to create a temporary keymap only for the duration of the
expansion.  I want to bind =oo-skeleton-next-position= to a key so I can quickly
move back and forth.  I know that tempel does this.  Tempel seems to just
temporariy add its map =tempel--map= to [[file:/home/luis/Documents/MyBlog/org/documentation/29.4-helpful-variable--minor-mode-overriding-map-alist.html][minor-mode-overriding-map-alist]].

Ideally I would like the map to be disabled after point leaves the bounds of the
skeleton.  I want to add some hook that tells me when I have moved to the last
position.  At first I was thinking of.  You could make end on the last skeleton
position but my concern is what if I will want to go back.

It is funny because I feel that the supposed weaknesses of skeletons are
precisely what their strenghts are what it is strengths are.

#+begin_src emacs-lisp
(defvar-keymap tempel-map
  :doc "Keymap to navigate across template fields."
  "<remap> <beginning-of-buffer>" #'tempel-beginning
  "<remap> <end-of-buffer>" #'tempel-end
  "<remap> <kill-sentence>" #'tempel-kill
  "<remap> <keyboard-escape-quit>" #'tempel-abort
  "<remap> <backward-paragraph>" #'tempel-previous
  "<remap> <forward-paragraph>" #'tempel-next
  ;; Use concrete keys because of org mode
  "M-RET" #'tempel-done
  "M-{" #'tempel-previous
  "M-}" #'tempel-next
  "M-<up>" #'tempel-previous
  "M-<down>" #'tempel-next)
#+end_src

There is also potential to feed the positions to [[https://github.com/abo-abo/avy][avy]] for an even faster way of jumping around.  Similar to =tempel= I want an abort skeleton command.
