#+title:sorting sitemap entries by date created
#+author:Luis Henriquez-Perez

I noticed the sitemap entries were not being sorted by filename as I expected.
I do not understand because the documentation in the manual say that the files
are sorted alphabetically by default.  I wish I could provide a function to sort
the files myself.

Based on the appearance of it looks like it actually sorts alphabetically based
on the title of the post and that it is case sensitive by default because posts
that are lower case are bumped down.  So it boils down to finding a way to get
the sorting to look my timestamps instead.  One option is to put the timestamp
in the title.  I do not want to do that.  I want the title to be separate from
the timestamp.  Another option is to put the date property into my blog posts.
Probably this is the easiest option?  If I do not include date org by default
uses date modified which is not what I want.  Having it this way means that the order will be changing all the time.

I would have to likely change the file timestamp to an org acceptable timestamp.

This [[https://www.reddit.com/r/emacs/comments/17fzthl/orgpublish_sorting_posts_based_on_data_in_the_org/][reddit post]].

Change timestamp to org timestamp.

#+begin_src emacs-lisp
#+end_src

#+begin_src emacs-lisp
(defun oo-add-date-to-blog-post ()
  (interactive)
  (string-match date2name-date-regexp (buffer-file-name))
  ;; (date2time-remove-data (buffer-file-name))
  )
#+end_src


In the manual.

I tell you, the easist way might be to just advise [[file:/home/luis/Documents/MyBlog/org/documentation/29.4-helpful-callable--org-publish-find-date.html][org-publish-find-date]], the function responsible for, during the call to [[file:/home/luis/Documents/MyBlog/org/documentation/29.4-helpful-callable--org-publish.html][org-publish]].

Obvious though I need to check the body of =org-publish-find-date= to see the conditions under which it is called.

#+begin_src emacs-lisp
(autolet! (flet! org-publish-find-date (file project)
            ;; Do not get the date the normal way.  Instead, use the timestamp
            ;; prepended to the front of the file.
            (file-name-nondirectory file)
            ()))
#+end_src
