* create better
:PROPERTIES:
:ID:       20250120T195821.674203
:END:

The idea of mine was inspired by multiple packages I have seen online--init
loaders: [[][Pinit-loader]] [[][Pel-init-loader]].  These are packages that load
parts of your emacs configuration for you but with the added benefit of doing
things like profiling your startup time or handling errors.

The former package requires you to name your files by loading order.  Whereas
=el-init-load= circimvents this by advising require and checking whether any of
the packages you load are.  Both packages do have a drawback: if compiling your
emacs configuration is a goal as it is for me the compiler does not know your
requiring these features since the function.

There is more to this though.  Thus far I have been maintaining a list of files
I require in my init file.  This is not the best design.  I have had problems.
Whenever I remove one of these files and forget to remove the corresponding line
I get an error.  Also I need to make sure these lines are in the right order
because order does matter--at least for some elements.  I no longer want to have
to actively maintain this and I also do not want to manage the order.  With this
in mind, my idea is to name files by number and keep.  Admittedly it is not as
pretty as just having names.

#+begin_src emacs-lisp
(require 'init-no-littering)
;; Built-in packages
(require 'init-abbrev)
(require 'init-auto-insert)
(require 'init-custom)
(require 'init-dired)
(require 'init-emacs-lock)
(require 'init-minibuffer)
(require 'init-saveplace)
(require 'init-vc-hooks)
(require 'init-window)
;; External packages
(require 'init-ace-window)
(require 'init-aggressive-indent)
(require 'init-avy)
(require 'init-buffer-terminator)
(require 'init-burly)
(require 'init-captain)
(require 'init-consult)
(require 'init-corfu)
(require 'init-corfu-history)
(require 'init-corfu-quick)
(require 'init-dashboard)
(require 'init-dirvish)
(require 'init-easy-escape)
(require 'init-emmet)
(require 'init-emms)
(require 'init-eshell)
#+end_src

* helper

I am going to be renaming a bunch of files here and I do want to ensure that I
do not have to do lots of editing as well.  Obviously I want to make this as
painless as possible.  I am surprised this does not exist but I could not find it.

#+begin_src emacs-lisp
;; I am a bit surprised this does not exist.
(defun! oo-rename-library (oldname newname)
  "Rename a library and replace all references.
OLDNAME is the current library name, and NEWNAME is the new name."
  (interactive "sOld library name: \nsNew library name: ")
  (message "oldname %S newname %S" oldname newname)
  (return!)
  (rename-file oldname newname)
  (set! regexp (regexp-quote oldname))
  (set! lisp-file-regexp ".+\\.el\\'")
  (set! files (append (directory-files (expand-file-name "lisp") t lisp-file-regexp)
                      (list user-init-file)
                      (directory-files (expand-file-name "test") t lisp-file-regexp)))
  ;; Replace the name of the symbol in file.
  (dolist (file files)
    (with-temp-file file
      (insert-file-contents file)
      (goto-char (point-min))
      (while (re-search-forward regexp nil t)
        (replace-match newname)))))
#+end_src
