#+title:draft using tempel with abbrevs
#+author:Luis Henriquez-Perez

I have had a desire to quickly.  It is such a pain to type links out manually.
And the link completion interface provided by org is not much better to be
honest.  Instead in this post I will show how I leverage abbrevs to make the
insertion of links as close to instantaneous as you can get.  And of course
several applications of this method.  Hello [[/home/luis/.config/emacs/lisp/050-base.el][050-base.el]] in the files [[https://github.com/Crandel/tempel-collection][tempel-collection]]. 

* expanding into a link

#+begin_src emacs-lisp
(defun! oo--expansion-config-link ()
  "Expand an org link for a configuration file."
  (setq doc-dir (expand-file-name "~/Documents/MyBlog/org/documentation/"))
  (set! lisp-dir (expand-file-name "lisp" user-emacs-directory))
  (appending! files (directory-files lisp-dir t (rx ".el" eol)))
  (pushing! files (expand-file-name user-init-file))
  (pushing! files (expand-file-name "early-init.el" user-emacs-directory))
  ;; Save a snapshot of my configuration file.
  (set! config-file (completing-read "" files))
  (set! html-file (expand-file-name (file-name-nondirectory file) doc-dir))
  (set! config-buffer (create-file-buffer config-file))
  (set! html-buffer (htmlize-buffer config-buffer))
  (unless (file-exists-p html-file)
    (with-current-buffer html-buffer
      (write-region (point-min) (point-max) html-file nil 'quiet)))
  (kill-buffer html-buffer)
  ;; TODO: make the file path relative.
  (insert (format "[[file:%s][%s]]" html-file (file-name-nondirectory path))))

(define-abbrev global-abbrev-table "clk" "" #'oo--expansion-config-link
  :enable-function #'oo--in-org-p)
(define-abbrev global-abbrev-table "clink" "" #'oo--expansion-config-link
  :enable-function #'oo--in-org-p)
#+end_src

* determine whether I am in a blog post

#+begin_src emacs-lisp
#+end_src

* package link documentation

Often when writing blog posts I have wanted to link to Emacs packages.  Writing
this I did not know how to do a completing-read for packages.

Looking at [[file:/home/luis/Documents/MyBlog/org/documentation/29.4-helpful--package-install.html][package-install]] I see that this is what is responsible for listing
packages.

#+begin_src emacs-lisp
(mapcan
 (lambda (elt)
   (and (or (and (or current-prefix-arg
                     package-install-upgrade-built-in)
                 (package--active-built-in-p (car elt)))
            (not (package-installed-p (car elt))))
        (list (symbol-name (car elt)))))
 package-archive-contents)
#+end_src

I do not know if it is worth putting this in a function yet so for now I will
just copy over the code.  I also did not know how to get the link that
corresponds to a package off the top of my head.  So I looked in
[[file:/home/luis/Documents/MyBlog/org/documentation/29.4-helpful--package-browse-url.html][package-browse-url]].

#+begin_src emacs-lisp
(cdr (assoc :url (package-desc-extras desc)))
#+end_src

[[https://github.com/phillord/pabbrev][pabbrev]]

#+begin_src emacs-lisp
(defun! oo--expand-package-link ()
  "Expand an org link for a configuration file."
  (set! desc (package--query-desc))
  (set! link (cdr (assoc :url (and desc (package-desc-extras desc)))))
  (insert (format "[[%s][%s]]" link (package-desc-name desc))))

(define-abbrev global-abbrev-table "plk" "" #'oo--expand-package-link
  :enable-function #'oo--in-org-p)
(define-abbrev global-abbrev-table "plink" "" #'oo--expand-package-link
  :enable-function #'oo--in-org-p)
#+end_src

* blog link to function documentation

#+begin_src emacs-lisp
(defun! oo--expand-function-documentation ()
  "Expand an org link for a configuration file."
  (setq doc-dir (expand-file-name "~/Documents/MyBlog/org/documentation/"))
  (set! helpful-switch-buffer-function #'ignore)
  (set! symbol (helpful--read-symbol "Callable: " (helpful--callable-at-point) #'fboundp))
  (setq html-file (expand-file-name (format "%s-helpful--%s.html" emacs-version symbol) doc-dir))
  (unless (file-exists-p html-file)
    (and (setq help-buffer (helpful-callable symbol))
         (setq html-buffer (htmlize-buffer help-buffer))
         (progn (with-current-buffer html-buffer
                  (write-region (point-min) (point-max) html-file nil 'quiet))
                (kill-buffer help-buffer)
                (kill-buffer html-buffer))))
  (insert (format "[[file:%s][%s]]"  html-file symbol)))

(define-abbrev global-abbrev-table "flk" "" #'oo--expand-function-documentation
  :enable-function #'oo--in-org-p)
#+end_src

* blog link to variable documentation

#+begin_src emacs-lisp
(defun! oo--expand-var-documentation ()
  "Expand an org link for a configuration file."
  (setq doc-dir (expand-file-name "../documentation"))
  (set! lisp-dir (expand-file-name "lisp" user-emacs-directory))
  (appending! files (directory-files lisp-dir t (rx ".el" eol)))
  (pushing! files (expand-file-name user-init-file))
  (pushing! files (expand-file-name "early-init.el" user-emacs-directory))
  (set! path (completing-read "" files))
  (insert (format "[[%s][%s]]"  path (file-name-nondirectory path))))
#+end_src

* blog link to another one of my posts

#+begin_src emacs-lisp
;; Prompt me for a config file.
(defun! oo-block-post ()
.  ""
  (set! blog-dir ())
  
  )
#+end_src
