#+title:draft timestamps to posts revisited
#+author:Luis Henriquez-Perez

Always look for an existing package that does what you want to do.  I do not
know why it did not occur to me to look for existing packages that add
timestamps but I should have, it would have saved me a lot of time.  I did
search now and found this nifty package [[foo][date2name]] which prepends a timestamp to
a file.  It has two dired commands, one for adding a timestamp, which is good
because I also have wanted to see how to write commands that work with dired
marking.

The only problem now is I have several files that were created a long time ago
and for those files I want the prefixed date to be the date of creation not the
current date.  Customizing the package to do this should
be as simple as advising a function.

First, of course, I need a way to get the file creation date and I have already come up with that with the help of chatGPT in a previous post.

#+begin_src emacs-lisp
(let* ((ctime (string-to-number (shell-command-to-string "stat -c %W draft_writing_tests.org")))
       (time (seconds-to-time ctime)))
  time)
#+end_src

I looked around the file a bit deciding what would be a good place to advise and
I settled on the [[file:/home/luis/Documents/MyBlog/org/documentation/29.4-helpful-callable--date2name-add-date-to-name.html][date2name-add-date-to-name]] function which is what the
user-facing functions [[file:/home/luis/Documents/MyBlog/org/documentation/29.4-helpful-callable--date2name-dired-add-date-to-name.html][date2name-dired-add-date-to-name]] and
[[file:/home/luis/Documents/MyBlog/org/documentation/29.4-helpful-callable--date2name-dired-add-datetime-to-name.html][date2name-dired-add-datetime-to-name]] use internally to compute the time to
prepend to file names.

Now I create an advice function.  The macros.

#+begin_src emacs-lisp
(defun! +date2name-dired-add-creationtime-to-name (arg)
  "Same as `date2name-dired-add-datetime-to-name' but use creation date instead."
  (interactive "P")
  ;; Instead of getting the modification time, get the creation time.
  (flet! file-attributes (filename)
    (seconds-to-time (string-to-number (shell-command-to-string (format "stat -c %%W %s" filename)))))
  (flet! date2name-file-attribute-modification-time #'identity)
  (date2name-dired-add-datetime-to-name arg))
#+end_src

#+begin_src emacs-lisp
(defun date2name-dired-add-datetime-to-name (arg)
  "Add date to filenames.
The filenames are all marked files in dired or the
file under the point if no files are marked.
If ARG is nil use the modification time of the file.
With one prefix arg, prompt for a time individually for each file.
With two prefix args prompt for one time for all files.
The format of the variable `date2name-datetime-format' is used
for the timestamp."
  (interactive "P")
  (date2name-add-date-to-name arg t))
#+end_src

