#+title:sorting when publishing
#+author:Luis Henriquez-Perez

Right now my website index page looks like complete garbage.  And this is one of
the reasons I have not updated my blog for a long time.  Maybe this is not a
good reason because I should be building the website incrementally not caring
about it is initial appearance and instead focusing on incremental improvements.

To clarify what I am talking about I have things setup in the [[][publish.el]]
file so that the blog.  You want to do this because you do not want to manually
"sync" the files.

The first thing I have want to do to sort the blog entries in the index by date
created.  The closest option I could find for this is =:sitemap-sort-files= which
sorts chronologically by modification time by default or the date if you specify
it at the top of the org file.  I hate sorting by modification time because it
means the order of my posts is inconsistent.

#+begin_src text
‘:sitemap-sort-files’
     How the files are sorted in the site map.  Set this to
     ‘alphabetically’ (default), ‘chronologically’ or
     ‘anti-chronologically’.  ‘chronologically’ sorts the files with
     older date first while ‘anti-chronologically’ sorts the files with
     newer date first.  ‘alphabetically’ sorts the files alphabetically.
     The date of a file is retrieved with ‘org-publish-find-date’.
#+end_src

My idea right now is to set =:sitemap-sort-files= to =chronologically= to get
org-publish to use the function [[file:/home/luis/Documents/MyBlog/org/documentation/29.4-helpful-callable--org-publish-find-date.html][org-publish-find-date]].  Then we override
=org-publish-find-date= with a function that returns the time of a file based on
the timestamped filename.  It is a bit indirect I know but it gets the job done.

#+begin_src emacs-lisp
(defun oo--publish-find-date (file _)
  (string-match "[0-9]\\{4\\}-[0-1][0-9]-[0-3][0-9]T[0-2][0-9].[0-5][0-9].[0-5][0-9]" file)
  (if-let (timestamp (match-string 0 file))
      (encode-time (parse-time-string (string-replace "." ":" timestamp)))
    (error "No timestamp")))

(advice-add 'org-publish-find-date :override 'oo--publish-find-date)
#+end_src

I got the regular expression from [[https://github.com/DerBeutlin/date2name.el][date2name]], a package for adding timestamps to
files.  I took a long time figuring out how to go from a timestamp string to an
elisp time object the same as when Emacs calls [[file:/home/luis/Documents/MyBlog/org/documentation/29.4-helpful-callable--current-time.html][current-time]].  chatGPT said to
use [[file:/home/luis/Documents/MyBlog/org/documentation/29.4-helpful-callable--parse-time-string.html][parse-time-string]] and then convert its output with [[file:/home/luis/Documents/MyBlog/org/documentation/29.4-helpful-callable--encode-time.html][encode-time]].  Luckily the
default timestamp format chosen by =date2name= is very similar to an "ISO 8601"
string that looks like =2020-01-15T16:12:21-08:00=.  All I had to do is replace
the =.= with =:=. 
