#+title:comparing and contrasting org blog with pure html and css
#+author:Luis Henriquez-Perez

I have struggled back and forth between continuing to write this blog in org
versus switching to a pure html and CSS blog.  I will be honest it is a tough
choice.

Embedding source code in a post is where org-mode shines.  With it is ability to
Org naturally is like a sort of "multi-mode" package akin to [[][mmm-mode]] and
[[][polymode]].  However, to understand how amazing org is for this we first
have to understand how this is handled by HTML and CSS.  To show code with
proper syntax highlighting you can use an external syntax highlighting with a
script like.  This seems to be what most
people do.  The downside is that this syntax highlighting is.

#+begin_src html
<div>
  <pre>
    <code class="language-elisp">
      (+ 1 1)
    </code>
  </pre>
</div>
#+end_src

I attempted to switch to a pure HTML and CSS blog and I encountered several
difficulties.

* from org to html

** source blocks

To be fair I expected the road to HTML and CSS source blocks to be rocky--at
least compared to how smooth and elegantly =org-publish= does it.  Instinctively,
I resist.  In contrast I had to make the decision to either use something like
[[][prism.js]] which would make my page rely on javascript and would not even
provide as good syntax highlighting as Emacs or take an approach like xah did.

** indentation

It was impossible for me to get indentation exactly the way I wanted it.  There
always seemed to be something wrong.

** multiple modes

Obviously it is really useful to be able to edit source blocks in the appropriate
major mode.  Org honestly is like a mini multiple mode package in that it allows
you to.  What I used is the package.  

At the end of the day I paused the move.  It would just take too much time.  And
there were too many things I needed to figure out.

I still have things to figure out here too.  For example, I the veratim org
emphasis marker translates to a =code= tag.

Essentially the problem with converting htmll with source blocks is that on the
one hand I want source blocks to be readable for me.

What I will say is that there is definitely more justification to use org for a blog
than org for an Emacs configuration.  There are clear advantages to having blog
posts in org mode.
