#+title:draft adding timestamps to posts
#+author:Luis Henriquez-Perez

Here I will discuss how I used file attribute of time to timestamp certain
posts.  I had been timestamping posts before but I stopped.  Partly cause I
"misplaced" the function I was using to create timestamped posts and partly
because I did not like all that boilerplate in front of files.  Now that I have
many draft posts and I cannot tell where the newer posts are that I realize I
definitely do need timestamped names.

My ext4 system actually stores the date created.  Ultimately I want to add this
as a function that can apply to files marked by dired.  But I should take this
one step at a time and write the function so that it works with just one file
first.

#+begin_src emacs-lisp
(defun oo--add-timestamp-to-file (file)
  ;; Check to see if the file has an exiting timestamp
  (unless (string-match-p )
    ;; Get the current creation time of the file.
    ()
    ;; Make the timesamp for the curr file.
    (format-time-string)
    (rename-file file newname)))

(defun oo--add-timestamp-to-file (file)
  "Rename FILE by appending a timestamp if it doesn't already have one."
  (let ((timestamp-regex "-[0-9]\\{8\\}_[0-9]\\{6\\}\\>")
        (timestamp (format-time-string "-%Y%m%d_%H%M%S"))
        (dirname (file-name-directory file))
        (basename (file-name-nondirectory file)))
    (unless (string-match-p timestamp-regex basename)
      (let* ((name (file-name-sans-extension basename))
             (ext (file-name-extension basename t))
             (newname (concat dirname name timestamp ext)))
        (rename-file file newname)
        newname))))  ;; Return the new filename
#+end_src

I can pick the date created from the result of the [[][stat]] command but I want to
I want to see if I can use the return value [[][Ffile-attributes]] instead.
According it to its documentation it can only give me the last access time, last
modification time, and last status change time.

#+begin_src emacs-lisp
(file-attributes (buffer-file-name))
;; => (nil 1 1000 998 (26548 43589 984039 438000) (26548 44732 970906 596000) (26548 44732 970906 596000) 1882 "-rw-r--r--" t 12468706 2050)
#+end_src

