It feels like it never ends.  I have done so much just to get a website.  I had
to teach myself the basic essentials to have a website in the first place.  I
had to get a domain, I had to get a host.  I decide how to structure my website
and what to use, pure html and css or org.  I had to write several block posts.
And even after all that my website looks like shit because I do not have any
css.  It is almost as.

https://niklasfasching.de/posts/just-enough-css/

* font
:PROPERTIES:
:ID:       20250124T144157.067348
:END:

Let us try to take it one step at a time.  I thought about it and I would wager
there is an 80-20 principle going on by which I mean 80% of the good look
"oompf" is created by 20% of the css.  I just need to identify what are the most
important aspects for me to tweak.  The first for me is the font.

* margin width

I do not know if margin width is the correct term for this but essentially I
want fringes on the left and right to be larger and force the text into the
center.  This I am not sure of how to do.  I think you need.

* center the title

With my naïve understanding of html these are the points that I see that are the
most pressing.

* do not underline links

The default underlining of links is ugly.  I want some sort of different
coloring but I do not want them to be underline unless the cursor hovers over
them.

* font

Find an attractive font.

Before and after.  Nothing insane but it is something.  I am closer to where I
want to be, which is the goal.

* how to style source blocks?

This is an open question.  I feel like there are many ways.  An explicit border
feels like too much but on the otherhand I want some sort of separation even if
it is just a different in background color. 
