One of the few external packages my emacs configuration depends on is =lgr=, a
logging library.  I use =lgr= to log to a =*log*= buffer.  For a while I have been
wanting to scrap it.  Not because it is a bad package.  On the contrary it is
quite featureful and possibly the best logging package out there.  However,
logging is so important I want to be able to do it earlier.  Specifically, all
the functions that I wrote which do some logging have to be defined after
package installatoin and that is inconvenient for me.  The way I use =lgr=
is simple enough where I thought it was worth it to just write my own.  Also
there were a few problems stemming up with lgr.  The biggest was that there was
no log cap, so the buffer grows indefinitely.  As long as my emacs is open and
more logs are being triggered the log buffer will grow larger and larger and
require ever more memory.  Making my logging.  Since you can define your own
appender, I am more the certain all of these problems can be fixed with lgr so
this is not to knock the package itself.

#+begin_src emacs-lisp
(defvar oo-log-buffer "*log*")

;; This is important because it prevents the buffer from growing indefinitely and causing performance problems.
(defvar oo-log-buffer-max 1000
  "Maximum number of lines in log buffer.")
#+end_src

The other thing was handling of duplicate messages.  When I looked at the
=*Messages*= buffer I noticed.

#+begin_src emacs-lisp
(defun! oo-log (type message &rest meta)
  (set! log (apply #'format message meta))
  (set! buffer (get-buffer-create oo-log-buffer))
  (with-current-buffer buffer
    ;; Add to buffer without constantly moving focus to the end.
    (save-excursion
      (goto-char (point-max))
      (save-excursion
        (forward-line -1)
        (goto-char (line-beginning-position))
        (set! regexp (rx bol "[" (1+ nonl) "]" (1+ nonl) (literal log) (optional space "(" space (group (1+ digit)) space ")")))
        (when (re-search-forward regexp (point-max) :no-error)
          (aif! (match-string 1)
              (replace-match (number-to-string (+ 1 (string-to-number it))) nil nil nil 1)
            (goto-char (match-end 0))
            (insert " ( 1 ) "))
          (return!)))
      ;; If last message matches this one, then replace it.
      (insert (format "[%s] %s\n" (upcase (symbol-name type)) log))
      ;; (when (+ foo foo)
      ;;   (goto-char (point-min))
      ;;   (delete-line))
      )))
#+end_src

Last thing I should do is ensure the buffer is readonly; do not want myself
accidentally deleting or editing log messages.

I am sure my =oo-log= function will get some more refinements later.  But for now
this is good enough.
