#+title: how I got a better idea of startup time
#+author: Luis Henriquez-Perez

The function [[file:/home/luis/Documents/MyBlog/org/documentation/29.4-helpful-callable--emacs-init-time.html][emacs-init-time]] is widely used by Emacs users as the primary
measure of the amount of time Emacs takes to start.  It computes the time
difference between two variables set during initialization, [[file:/home/luis/Documents/MyBlog/org/documentation/29.4-helpful--after-init-time.html][after-init-time]] and
[[file:/home/luis/Documents/MyBlog/org/documentation/29.4-helpful--before-init-time.html][before-init-time]].  As I became more serious about reducing the startup time of
my Emacs configuration I was naturally curious about details of initialization.
Specifically, I was interested in where the =after-init-time= and =before-init-time=
were set in relation to other events happening during Emacs startup.  I read up
on all this in [[file:../documentation/29.4-info-elisp-startup-summary.html][the manual]] where initialization is divided into steps.  One of
the first things that stuck out to me was how many events beyond loading the
Emacs init file there were between the =before-init-time= and =after-init-time=.  Of
the 15 events within these times.  I was also surprised that the =after-init-hook=
and =emacs-startup-hook= were not among these events and consequently not included
in the measurement produced via =emacs-init-time=.  Because running these hooks takes
/some/ time and particularly because.


In the startup summary.  In fact, of the N
steps I also things I expected to be counted towards initialization, namely the
=after-init-hook= and the =emacs-startup-hook= were excluded.
 
I want a better measure of the "absolute" Emacs startup time, which I define as
the "total" time Emacs takes to startup.

#+begin_src emacs-lisp
#+end_src

There will always be some non-negotiable things Emacs has to spend time on
during initialization but when I am profiling I want to only consider the
effect my configuration has on Emacs startup.  So I set out to take a few time
measurements of my own.  Below I am compute exactly how much time Emacs
takes to compute it own stuff. 

#+begin_src emacs-lisp
(defvar oo-before-load-time (current-time))
(require! :profile t)
(defvar oo-after-load-time (current-time))
(defun oo-startup-info ()
  (interactive)
  (let ((a (float-time (time-subtract oo-before-load-time before-init-time)))
        (b (float-time (time-subtract oo-after-load-time oo-before-load-time)))
        (c (float-time (time-subtract after-init-time oo-after-load-time))))
    (message "before -> %0.2f | loading elapsed %0.2f | done %0.2f" a b c)))
#+end_src

This following is the output I got from the messages buffer.  So the time from
=before-init-time= to when I started to load my files was =0.50= seconds.  The time
it took to actually load my configuration files was =0.65= seconds.  And the time from
when the loading was done to just before =after-init-hook= was run was =0.01=
seconds.  One thing to take from this is that.   

And =emacs-init-time= =1.15= seconds.  It is no coincidence that the init time is
the sum of the before and loading elapsed time ~0.50 + 065 = 1.15~.
[[file:/home/luis/Documents/MyBlog/org/documentation/29.4-helpful-callable--emacs-init-time.html][emacs-init-time]] 

#+begin_src text
before -> 0.50 | loading elapsed 0.65 | done 0.01
#+end_src

#+begin_src text
[INFO] Finished running `after-init-hook' in 0.37 seconds
...
[INFO] Finished running `emacs-startup-hook' in 0.23 seconds
#+end_src

The total init time is ~(+ 0.50 0.65 0.01 0.37 0.23)~ which is approximately
=1.76= seconds.  And the init time that I am responsible for is ~(+ 0.65 0.37
0.23)~ which adds to =1.25= seconds.  This is why I find the =emacs-init-time= a bit
misleading.
[[file:/home/luis/Documents/MyBlog/org/documentation/29.4-helpful-callable--time-subtract.html][time-subtract]] 

Additionally I logged the amount of time spent running the =after-init-hook= and
the =emacs-startup-hook= which I also considered part of my effect on startup.

#+begin_src emacs-lisp
(defhook! record-after-init-hook-start-time (after-init-hook)
  "Record the start of `after-init-hook'."
  :depth -100
  (oo-log 'info "Running `after-init-hook'...")
  (set-register :after-init-start (float-time)))

(defsubst oo-hundredths (n)
  "Return N rounded to the nearest hundredth."
  (/ (fround (* n 100)) 100.0))

(defhook! record-after-init-hook-end-time (after-init-hook :depth 100)
  "Record the end of `after-init-hook'."
  (set! start (get-register :after-init-start))
  (set! time (oo-hundredths (- (float-time) start)))
  (set-register :after-init-hook-time time)
  (oo-log 'info "Finished running `after-init-hook' in %.2f seconds" time))

(defhook! record-emacs-startup-hook-start-time (emacs-startup-hook :depth -100)
  "Record the start of `emacs-startup-hook'."
  (oo-log 'info "Running `emacs-startup-hook'...")
  (set-register :emacs-startup-start (float-time)))

(defhook! record-emacs-startup-hook-end-time (emacs-startup-hook :depth 100)
  "Record the end of `emacs-startup-hook'."
  (set! start (get-register :emacs-startup-start))
  (set! time (oo-hundredths (- (float-time) start)))
  (set-register :emacs-startup-hook-time time)
  (oo-log 'info "Finished running `emacs-startup-hook' in %.2f seconds" time))
#+end_src

I know have a more.

Steps 3 through 13 are internal steps for Emacs
initialization that are out of the users control.  Furthermore, the I wanted to
know then what portion of the startup time was my responsibility.  I also
noticed that =after-init-time= is set just before. what =emacs-init-time= does not
measure: Namely the time it takes to run the [[file:/home/luis/Documents/MyBlog/org/documentation/29.4-helpful--after-init-hook.html][after-init-hook]] and
[[file:/home/luis/Documents/MyBlog/org/documentation/29.4-helpful--emacs-startup-hook.html][emacs-startup-hook]].  I am not sure why this is not included considering that
these hooks do consume some time.  Particularly when trying to improve Emacs
startup time I found it useful to focus specifically on the effect you have on
Emacs initialization.

But if you look at everything that happens in the startup summary steps, I am
not responsible for steps 3 through 13 (inclusive).  The init file is loaded on
step 14.  Also note that =after-init-time= is set /before/ either [[file:/home/luis/Documents/MyBlog/org/documentation/29.4-helpful--after-init-hook.html][after-init-hook]] or
[[file:/home/luis/Documents/MyBlog/org/documentation/29.4-helpful--emacs-startup-hook.html][emacs-startup-hook]] is set, meaning that the time these hooks take is not
included in the init time.  This is strange to me because I am the one who adds
to these hooks and they do consume time so they should also be considered.  I do
not know, essentially I would classify the "real" init time as everything you as
a user are responsible for, in other words, the real difference in time that
your configuration is adding to Emacs's startup.  This would be the time taken
to load your configuration files + the time taken to run =after-init-hook= + the
time taken to run =emacs-startup-hook=.
