#+title: how I got a better idea of startup time
#+author: Luis Henriquez-Perez

The function [[file:/home/luis/Documents/MyBlog/org/documentation/29.4-helpful-callable--emacs-init-time.html][emacs-init-time]] is widely used by Emacs users as the primary
measure of the amount of time Emacs takes to start.  It computes the time
difference between two variables set during initialization, [[file:/home/luis/Documents/MyBlog/org/documentation/29.4-helpful--after-init-time.html][after-init-time]] and
[[file:/home/luis/Documents/MyBlog/org/documentation/29.4-helpful--before-init-time.html][before-init-time]].  As I became more serious about reducing the startup time of
my Emacs configuration I was naturally curious about details of initialization.
I wanted to know where =after-init-time= and =before-init-time= were set in relation
to other events happening during Emacs startup.  I read up on all this in the
manual's [[file:../documentation/29.4-info-elisp-startup-summary.html][startup summary]].  I noticed there were many steps besides loading the
Emacs init file there were between the =before-init-time= and =after-init-time=.  Of
the 15 events within these times 14 of them are not related to.  I was surprised
that the =after-init-hook= and =emacs-startup-hook= were not included in the
measurements for =emacs-init-time=.  My logic was that because running these hooks
takes /some/ time and the hooks added are determined by the user.

There will always be some non-negotiable things Emacs has to spend time on
during initialization but when I am profiling I want to only consider the
effect my configuration has on Emacs startup.  To that end I want to "isolate"
or separate the time my configuration takes to load, step 14 in the startup
summary, from what happens before and after it.  I came up with this code

#+begin_src emacs-lisp
(defvar oo-before-load-time (current-time))
(require! :profile t)
(defvar oo-after-load-time (current-time))
(defun oo-startup-info ()
  (interactive)
  (let ((a (float-time (time-subtract oo-before-load-time before-init-time)))
        (b (float-time (time-subtract oo-after-load-time oo-before-load-time)))
        (c (float-time (time-subtract after-init-time oo-after-load-time))))
    (message "before -> %0.2f | loading elapsed %0.2f | done %0.2f" a b c)))
#+end_src

This following is the output I got from the messages buffer.  The time from
=before-init-time= to when I started to load my files was =0.50= seconds.  The time
it took to actually load my configuration files was =0.65= seconds.  And the time from
when the loading was done to just before =after-init-hook= was run was =0.01=
seconds.  One thing to take from this is that.   

And =emacs-init-time= =1.15= seconds.  It is no coincidence that the init time is
the sum of the before and loading elapsed time ~0.50 + 065 = 1.15~.
[[file:/home/luis/Documents/MyBlog/org/documentation/29.4-helpful-callable--emacs-init-time.html][emacs-init-time]] 

#+begin_src text
before -> 0.50 | loading elapsed 0.65 | done 0.01
#+end_src

#+begin_src text
[INFO] Finished running `after-init-hook' in 0.37 seconds
...
[INFO] Finished running `emacs-startup-hook' in 0.23 seconds
#+end_src

The total init time is ~(+ 0.50 0.65 0.01 0.37 0.23)~ which is approximately =1.76=
seconds.  And the init time that I am responsible for is ~(+ 0.65 0.37 0.23)~
which adds to =1.25= seconds.  This is why I find the =emacs-init-time= a bit
misleading.

Additionally I logged the amount of time spent running the =after-init-hook= and
the =emacs-startup-hook= which I also considered part of my effect on startup.

#+begin_src emacs-lisp
(defhook! record-after-init-hook-start-time (after-init-hook)
  "Record the start of `after-init-hook'."
  :depth -100
  (oo-log 'info "Running `after-init-hook'...")
  (set-register :after-init-start (float-time)))

(defsubst oo-hundredths (n)
  "Return N rounded to the nearest hundredth."
  (/ (fround (* n 100)) 100.0))

(defhook! record-after-init-hook-end-time (after-init-hook :depth 100)
  "Record the end of `after-init-hook'."
  (set! start (get-register :after-init-start))
  (set! time (oo-hundredths (- (float-time) start)))
  (set-register :after-init-hook-time time)
  (oo-log 'info "Finished running `after-init-hook' in %.2f seconds" time))

(defhook! record-emacs-startup-hook-start-time (emacs-startup-hook :depth -100)
  "Record the start of `emacs-startup-hook'."
  (oo-log 'info "Running `emacs-startup-hook'...")
  (set-register :emacs-startup-start (float-time)))

(defhook! record-emacs-startup-hook-end-time (emacs-startup-hook :depth 100)
  "Record the end of `emacs-startup-hook'."
  (set! start (get-register :emacs-startup-start))
  (set! time (oo-hundredths (- (float-time) start)))
  (set-register :emacs-startup-hook-time time)
  (oo-log 'info "Finished running `emacs-startup-hook' in %.2f seconds" time))
#+end_src
